/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.keyboard;

import com.control.Variables;
import java.awt.IllegalComponentStateException;
import java.awt.Point;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;

/**
 *
 * @author Fermentador 7 Litros
 */
public class Password extends javax.swing.JFrame {

    private static final long serialVersionUID = 01;
    JPopupMenu pop;
    JKeyboardPane teclado;
    com.control.AjustesControlTemperatura abrir = new com.control.AjustesControlTemperatura();
    com.control.AjustesAgitador agitador = new com.control.AjustesAgitador();
    com.control.AjustespH pH = new com.control.AjustespH();
    com.control.AjustesOD OD = new com.control.AjustesOD();
    com.control.AjustesEsterilizacion esterilizacion = new com.control.AjustesEsterilizacion();
    com.control.AjustesPresion presion = new com.control.AjustesPresion();

    /**
     * Creates new form TecladoLetras
     */
    public Password() {
        initComponents();
        jPasswordField1.setText(null);
        jTextField1.setText(null);
        //setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Accept = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JP-Biolab  Fermentors & Bioreactors");
        setAlwaysOnTop(true);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/com/images/erlenmeyer.jpg")).getImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Contraseña");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Usuario");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/LogoJPSinFondo.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);

        Accept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/symbol-check-icon.png"))); // NOI18N
        Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptActionPerformed(evt);
            }
        });

        Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/delete-icon.png"))); // NOI18N
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Accept, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Accept, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(Cancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        try {
            pop = new JPopupMenu();
            teclado = new JKeyboardPane(Password.jPasswordField1);
            pop.add(teclado);

            if (jPasswordField1.isShowing()) {
                Point location = Password.jPasswordField1.getLocationOnScreen();
                System.out.println(location);
                pop.setLocation(location.x + Password.jPasswordField1.getSize().width, location.y);
                pop.setVisible(true);
            }
        } catch (IllegalComponentStateException ex) {
            System.err.println("No se puede obtener la ubicación del text field porque aún no está visible.");
        }
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        pop.setVisible(false);
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        try {
            pop = new JPopupMenu();
            teclado = new JKeyboardPane(Password.jTextField1);
            pop.add(teclado);

            if (jTextField1.isShowing()) {
                Point location = Password.jTextField1.getLocationOnScreen();
                System.out.println(location);
                pop.setLocation(location.x + Password.jTextField1.getSize().width, location.y);
                pop.setVisible(true);
            }
        } catch (IllegalComponentStateException ex) {
            System.err.println("No se puede obtener la ubicación del text field porque aún no está visible.");
        }
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        pop.setVisible(false);
    }//GEN-LAST:event_jTextField1FocusLost

    private void AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptActionPerformed
        if ("ADMIN".equals(jTextField1.getText())) {
            char[] arrayC = jPasswordField1.getPassword();
            String pass = new String(arrayC);
            if ("3892".equals(pass)) {//Si la contraseña es correcta, craga los valores de las variables a los TextField
                if (Variables.ajusteAgitador) {
                    agitador.setVisible(true);
                    Variables.añadirEvento("Ingreso a parametros de Agitación");
                }
                if (Variables.ajusteTemperatura) {
                    abrir.setVisible(true);
                    Variables.añadirEvento("Ingreso a parametros de temperatura");
                }
                if (Variables.ajustepH) {
                    pH.setVisible(true);
                    Variables.añadirEvento("Ingreso a parametros de pH");
                }
                if (Variables.ajusteOD) {
                    OD.setVisible(true);
                    Variables.añadirEvento("Ingreso a parametros de Oxigeno disuelto");
                }
                if (Variables.ajusteEsterilizacion) {
                    esterilizacion.setVisible(true);
                    Variables.añadirEvento("Ingreso a parametros de Esterilización");
                }
                if (Variables.ajustePresion) {
                    presion.setVisible(true);
                    Variables.añadirEvento("Ingreso a parametros de Esterilización");
                }
                Variables.ajusteAgitador = false;
                Variables.ajusteTemperatura = false;
                Variables.ajustepH = false;
                Variables.ajusteOD = false;
                Variables.ajusteEsterilizacion = false;
                Variables.ajustePresion = false;
                Variables.contraseña = String.valueOf(jPasswordField1.getPassword());
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Usuario o Contraseña son incorrectos");
                Variables.añadirEvento("Ingreso fallido a parametros");
            }
        } else {
            if ("JPINGLOBAL".equals(jTextField1.getText())) {
                char[] arrayC = jPasswordField1.getPassword();
                String pass = new String(arrayC);
                if ("900409216".equals(pass)) {
                    Variables.login = true;
                    Variables.usuario = jTextField1.getText();
                    Variables.contraseña = String.valueOf(jPasswordField1.getPassword());
                    Variables.rol = "Administrador";
                    Variables.añadirEvento("Accedio como super usuario");
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Usuario o Contraseña son incorrectos");
                    Variables.añadirEvento("Ingreso fallido como super usuario");
                }
            } else {
                Variables.login = false;
                for (int i = 0; i < Variables.usuarios.size(); i++) {
                    char[] arrayC = jPasswordField1.getPassword();
                    String pass = new String(arrayC);
                    if (Variables.usuarios.get(i).equals(jTextField1.getText()) && Variables.claves.get(i).equals(pass)) {
                        Variables.login = true;
                        Variables.usuario = Variables.usuarios.get(i);
                        Variables.contraseña = Variables.claves.get(i);
                        Variables.rol = Variables.roles.get(i);
                        Variables.añadirEvento("Accedio como " + Variables.usuario);
                        dispose();
                    }
                }
                if (!Variables.login) {
                    Variables.usuario = "";
                    Variables.contraseña = "";
                    Variables.rol = "";
                    JOptionPane.showMessageDialog(this, "Usuario o Contraseña son incorrectos");
                    Variables.añadirEvento("Ingreso fallido");
                }
            }
        }
    }//GEN-LAST:event_AcceptActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        Variables.ajusteAgitador = false;
        Variables.ajusteTemperatura = false;
        Variables.ajustepH = false;
        Variables.ajusteOD = false;
        Variables.ajusteCO2 = false;
        Variables.ajusteRedox = false;
        Variables.ajustePresion = false;
        Variables.ajusteEsterilizacion = false;
        dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Variables.ajusteAgitador = false;
        Variables.ajusteTemperatura = false;
        Variables.ajustepH = false;
        Variables.ajusteOD = false;
        Variables.ajusteCO2 = false;
        Variables.ajusteRedox = false;
        Variables.ajustePresion = false;
        Variables.ajusteEsterilizacion = false;
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accept;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPasswordField jPasswordField1;
    public static javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
