/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.info;

import com.control.Variables;
import com.keyboard.JKeyboardPane;
import java.awt.Color;
import java.util.Calendar;
import java.util.Formatter;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;

/**
 *
 * @author Fermentador 7 Litros
 */
public class Batch extends javax.swing.JFrame {
    private static final long serialVersionUID = 01;
    JPopupMenu pop;
    JKeyboardPane teclado;
    /**
     * Creates new form Batch
     */
    public Batch() {
        initComponents();
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/com/images/logo.png")).getImage());
        jPanel1.setBackground(Color.WHITE);
        Calendar cal = new GregorianCalendar();
        int hora=cal.get(Calendar.HOUR_OF_DAY);
        int minuto=cal.get(Calendar.MINUTE);
        int segundo=cal.get(Calendar.SECOND);
        Formatter formato2H = new Formatter();  // Formato de la hora
        formato2H.format("%02d", hora);
        String hora2 = formato2H.toString();    // String de la hora dos cifras
        Formatter formato2M = new Formatter();
        formato2M.format("%02d", minuto);
        String minuto2 = formato2M.toString();  // String de minutos dos cifras
        Formatter formato2S = new Formatter();
        formato2S.format("%02d", segundo);
        String segundo2 = formato2S.toString(); // String de segundos dos cifras
        TextHora.setText(hora2+":"+minuto2+":"+segundo2);
        TextFecha.setText(Integer.toString(cal.get(Calendar.DAY_OF_MONTH))+"/"+Integer.toString(cal.get(Calendar.MONTH)+1)+"/"+Integer.toString(cal.get(Calendar.YEAR)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TextExperimentador = new javax.swing.JTextField();
        TextIdentificacion = new javax.swing.JTextField();
        TextBatch = new javax.swing.JTextField();
        TextFecha = new javax.swing.JTextField();
        TextHora = new javax.swing.JTextField();
        Accept = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        TextObser = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JP-Biolab   Fermentors & Bioreactors");
        setAlwaysOnTop(true);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/LogoJPSinFondo.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Experimentador:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("No Identificación:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Batch:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Fecha Inicio:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Hora Inicio:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Observaciones:");

        TextExperimentador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextExperimentador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextExperimentadorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextExperimentadorFocusLost(evt);
            }
        });

        TextIdentificacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextIdentificacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextIdentificacionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextIdentificacionFocusLost(evt);
            }
        });

        TextBatch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextBatch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextBatchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextBatchFocusLost(evt);
            }
        });

        TextFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        TextHora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Accept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/symbol-check-icon.png"))); // NOI18N
        Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptActionPerformed(evt);
            }
        });

        Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/delete-icon.png"))); // NOI18N
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        TextObser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextObser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextObserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextObserFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextObser, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Accept, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextExperimentador, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextBatch, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextHora, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(41, 41, 41))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextExperimentador, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextBatch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TextHora, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextObser, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Accept, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextExperimentadorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextExperimentadorFocusGained
        pop = new JPopupMenu();
        teclado=new JKeyboardPane(TextExperimentador);
        pop.add(teclado);
	pop.setVisible(true);
	pop.setLocation(TextExperimentador.getLocationOnScreen().x+TextExperimentador.getSize().width, TextExperimentador.getLocationOnScreen().y);
    }//GEN-LAST:event_TextExperimentadorFocusGained

    private void TextExperimentadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextExperimentadorFocusLost
        pop.setVisible(false);
    }//GEN-LAST:event_TextExperimentadorFocusLost

    private void TextIdentificacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextIdentificacionFocusGained
        pop = new JPopupMenu();
        teclado=new JKeyboardPane(TextIdentificacion);
        pop.add(teclado);
	pop.setVisible(true);
	pop.setLocation(TextIdentificacion.getLocationOnScreen().x+TextIdentificacion.getSize().width, TextIdentificacion.getLocationOnScreen().y);
    }//GEN-LAST:event_TextIdentificacionFocusGained

    private void TextIdentificacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextIdentificacionFocusLost
        pop.setVisible(false);
    }//GEN-LAST:event_TextIdentificacionFocusLost

    private void TextBatchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextBatchFocusGained
        pop = new JPopupMenu();
        teclado=new JKeyboardPane(TextBatch);
        pop.add(teclado);
	pop.setVisible(true);
	pop.setLocation(TextBatch.getLocationOnScreen().x+TextBatch.getSize().width, TextBatch.getLocationOnScreen().y);
    }//GEN-LAST:event_TextBatchFocusGained

    private void TextBatchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextBatchFocusLost
        pop.setVisible(false);
    }//GEN-LAST:event_TextBatchFocusLost

    private void AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptActionPerformed
        if("".equals(TextBatch.getText()) || "".equals(TextExperimentador.getText()) || "".equals(TextIdentificacion.getText()))
        {
            int continuar = JOptionPane.showConfirmDialog(this,"No ha llenado todos los campos"
                                                            + "\n¿Desea continuar?");
                    if(continuar == JOptionPane.YES_OPTION){//si se selecciona SI 
                        dispose();
                        Variables.IngresoDatos=1;                        
                    }
        }
        else
        {
            Variables.IngresoDatos=0;
            dispose();
        }
    }//GEN-LAST:event_AcceptActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void TextObserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextObserFocusGained
        pop = new JPopupMenu();
        teclado=new JKeyboardPane(TextObser);
        pop.add(teclado);
	pop.setVisible(true);
	pop.setLocation(TextObser.getLocationOnScreen().x+TextObser.getSize().width, TextObser.getLocationOnScreen().y);
    }//GEN-LAST:event_TextObserFocusGained

    private void TextObserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextObserFocusLost
        pop.setVisible(false);
    }//GEN-LAST:event_TextObserFocusLost

    public void CargarInfo(){
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Batch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Batch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Batch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Batch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Batch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accept;
    private javax.swing.JButton Cancel;
    public static javax.swing.JTextField TextBatch;
    public static javax.swing.JTextField TextExperimentador;
    public static javax.swing.JTextField TextFecha;
    public static javax.swing.JTextField TextHora;
    public static javax.swing.JTextField TextIdentificacion;
    public static javax.swing.JTextField TextObser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
