/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.views;

import com.control.Variables;
import com.keyboard.JNumBoardPane;
import com.keyboard.PopUpAsignacion;
import com.model.Bioreactor;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author JuanDavid
 */
public class BombasPeristalticas extends javax.swing.JPanel {

    private static final long serialVersionUID = 01;
    private JNumBoardPane tecladoNumerico;
    private JPopupMenu pop;
    private PopUpAsignacion popAsigna;
    private CalibracionBomba calibra;

    public static boolean focusGained = false;

    /**
     * Creates new form BombasPeristalticas
     */
    public BombasPeristalticas() {
        initComponents();
        jPanel1.setBackground(Color.WHITE);
        jPanel2.setBackground(Color.WHITE);
        jPanel3.setBackground(Color.WHITE);
        bomba1On.setBackground(Color.gray);
        bomba1Off.setBackground(Color.RED);
        bomba2On.setBackground(Color.gray);
        bomba2Off.setBackground(Color.RED);
        bomba3On.setBackground(Color.gray);
        bomba3Off.setBackground(Color.RED);

        runBomba1.setName("1");
        runBomba2.setName("2");
        runBomba3.setName("3");

        asignacionBomba1.setName("1");
        asignacionBomba2.setName("2");
        asignacionBomba3.setName("3");

        for (Bioreactor bio : Variables.bioreactores) {
            if (Variables.idBioreactor == bio.getId()) {
                SetPointBomba1.setText("" + bio.getBomba(0).getPorcentajeDuty());
                SetPointBomba2.setText("" + bio.getBomba(1).getPorcentajeDuty());
                SetPointBomba3.setText("" + bio.getBomba(2).getPorcentajeDuty());

                PeriodoBomba1.setText("" + bio.getBomba(0).getTiempoEncendidoSegundos());
                PeriodoBomba2.setText("" + bio.getBomba(1).getTiempoEncendidoSegundos());
                PeriodoBomba3.setText("" + bio.getBomba(2).getTiempoEncendidoSegundos());

                asignacionBomba1.setText("" + bio.getBomba(0).getParametros().getAsignacionBomba());
                asignacionBomba2.setText("" + bio.getBomba(1).getParametros().getAsignacionBomba());
                asignacionBomba3.setText("" + bio.getBomba(2).getParametros().getAsignacionBomba());
            }
        }
        SetPointBomba1.repaint();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bomba1On = new javax.swing.JButton();
        bomba1Off = new javax.swing.JButton();
        SetPointBomba1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        PeriodoBomba1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        runBomba1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        asignacionBomba1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        bomba2On = new javax.swing.JButton();
        bomba2Off = new javax.swing.JButton();
        SetPointBomba2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PeriodoBomba2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        runBomba2 = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        asignacionBomba2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        SetPointBomba3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PeriodoBomba3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        asignacionBomba3 = new javax.swing.JTextField();
        runBomba3 = new javax.swing.JToggleButton();
        bomba3Off = new javax.swing.JButton();
        bomba3On = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1280, 629));
        setMinimumSize(new java.awt.Dimension(1280, 629));
        setPreferredSize(new java.awt.Dimension(1280, 629));

        jPanel1.setFocusable(false);
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 630));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 630));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 630));
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bomba #1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 0, 14))); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(600, 300));
        jPanel2.setMinimumSize(new java.awt.Dimension(600, 300));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 300));

        bomba1On.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bomba1On.setText("ON");
        bomba1On.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bomba1OnActionPerformed(evt);
            }
        });

        bomba1Off.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bomba1Off.setText("OFF");
        bomba1Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bomba1OffActionPerformed(evt);
            }
        });

        SetPointBomba1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SetPointBomba1.setText("0");
        SetPointBomba1.setToolTipText("SetPoint Bomba 1");
        SetPointBomba1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SetPointBomba1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SetPointBomba1FocusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("SetPoint");

        PeriodoBomba1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        PeriodoBomba1.setText("0");
        PeriodoBomba1.setToolTipText("Periodo Bomba 1");
        PeriodoBomba1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PeriodoBomba1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PeriodoBomba1FocusLost(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Periodo(s)");

        runBomba1.setText("RUN");
        runBomba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runBomba1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Asignación de Bomba:");

        asignacionBomba1.setEditable(false);
        asignacionBomba1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        asignacionBomba1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        asignacionBomba1.setText("Ninguno");
        asignacionBomba1.setToolTipText("Asignacion Bomba 1");
        asignacionBomba1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                asignacionBomba1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                asignacionBomba1FocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SetPointBomba1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(PeriodoBomba1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(asignacionBomba1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(bomba1On, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(bomba1Off, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(runBomba1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(71, 71, 71))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(runBomba1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bomba1On, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bomba1Off, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PeriodoBomba1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SetPointBomba1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(asignacionBomba1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 11, 600, 270);

        jPanel3.setBackground(java.awt.Color.red);
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bomba #2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 0, 14))); // NOI18N
        jPanel3.setToolTipText("");
        jPanel3.setMaximumSize(new java.awt.Dimension(600, 300));
        jPanel3.setMinimumSize(new java.awt.Dimension(600, 300));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(600, 300));
        jPanel3.setLayout(null);

        bomba2On.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bomba2On.setText("ON");
        bomba2On.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bomba2OnActionPerformed(evt);
            }
        });
        jPanel3.add(bomba2On);
        bomba2On.setBounds(120, 40, 95, 50);

        bomba2Off.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bomba2Off.setText("OFF");
        bomba2Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bomba2OffActionPerformed(evt);
            }
        });
        jPanel3.add(bomba2Off);
        bomba2Off.setBounds(280, 40, 95, 50);

        SetPointBomba2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SetPointBomba2.setText("0");
        SetPointBomba2.setToolTipText("Setpoint Bomba 2");
        SetPointBomba2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SetPointBomba2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SetPointBomba2FocusLost(evt);
            }
        });
        jPanel3.add(SetPointBomba2);
        SetPointBomba2.setBounds(200, 130, 63, 34);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("SetPoint");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(130, 130, 51, 17);

        PeriodoBomba2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        PeriodoBomba2.setText("0");
        PeriodoBomba2.setToolTipText("Periodo Bomba 2");
        PeriodoBomba2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PeriodoBomba2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PeriodoBomba2FocusLost(evt);
            }
        });
        jPanel3.add(PeriodoBomba2);
        PeriodoBomba2.setBounds(440, 130, 62, 34);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Periodo(s)");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(370, 130, 62, 17);

        runBomba2.setText("RUN");
        runBomba2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runBomba2ActionPerformed(evt);
            }
        });
        jPanel3.add(runBomba2);
        runBomba2.setBounds(430, 40, 95, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Asignación de Bomba:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(240, 190, 135, 17);

        asignacionBomba2.setEditable(false);
        asignacionBomba2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        asignacionBomba2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        asignacionBomba2.setText("Ninguno");
        asignacionBomba2.setToolTipText("Asignacion Bomba 2");
        asignacionBomba2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                asignacionBomba2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                asignacionBomba2FocusLost(evt);
            }
        });
        jPanel3.add(asignacionBomba2);
        asignacionBomba2.setBounds(120, 220, 403, 23);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(670, 11, 600, 270);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bomba #3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 0, 14))); // NOI18N
        jPanel4.setMaximumSize(new java.awt.Dimension(600, 300));
        jPanel4.setMinimumSize(new java.awt.Dimension(600, 300));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(null);

        SetPointBomba3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SetPointBomba3.setText("0");
        SetPointBomba3.setToolTipText("SetPoint Bomba 1");
        SetPointBomba3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SetPointBomba3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SetPointBomba3FocusLost(evt);
            }
        });
        jPanel4.add(SetPointBomba3);
        SetPointBomba3.setBounds(230, 120, 63, 34);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("SetPoint");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(150, 120, 51, 17);

        PeriodoBomba3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        PeriodoBomba3.setText("0");
        PeriodoBomba3.setToolTipText("Periodo Bomba 1");
        PeriodoBomba3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PeriodoBomba3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PeriodoBomba3FocusLost(evt);
            }
        });
        jPanel4.add(PeriodoBomba3);
        PeriodoBomba3.setBounds(470, 120, 62, 34);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Periodo(s)");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(390, 120, 62, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Asignación de Bomba:");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(280, 190, 135, 17);

        asignacionBomba3.setEditable(false);
        asignacionBomba3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        asignacionBomba3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        asignacionBomba3.setText("Ninguno");
        asignacionBomba3.setToolTipText("Asignacion Bomba 1");
        asignacionBomba3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                asignacionBomba3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                asignacionBomba3FocusLost(evt);
            }
        });
        jPanel4.add(asignacionBomba3);
        asignacionBomba3.setBounds(140, 220, 400, 25);

        runBomba3.setText("RUN");
        runBomba3.setName("3"); // NOI18N
        runBomba3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runBomba3ActionPerformed(evt);
            }
        });
        jPanel4.add(runBomba3);
        runBomba3.setBounds(450, 30, 95, 50);

        bomba3Off.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bomba3Off.setText("OFF");
        bomba3Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bomba3OffActionPerformed(evt);
            }
        });
        jPanel4.add(bomba3Off);
        bomba3Off.setBounds(300, 30, 95, 50);

        bomba3On.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bomba3On.setText("ON");
        bomba3On.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bomba3OnActionPerformed(evt);
            }
        });
        jPanel4.add(bomba3On);
        bomba3On.setBounds(140, 30, 95, 50);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(336, 299, 600, 270);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/symbol-check-icon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(613, 587, 65, 41);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void creaPopA(JTextField f) {
        if (popAsigna != null) {
            if (popAsigna.isVisible()) {
                popAsigna.setVisible(false);
            } else {
                popAsigna = new PopUpAsignacion(f);
                popAsigna.setVisible(true);
                popAsigna.setLocation(f.getLocationOnScreen().x + f.getSize().width,
                        f.getLocationOnScreen().y);
            }
        } else {
            popAsigna = new PopUpAsignacion(f);
            popAsigna.setVisible(true);
            popAsigna.setLocation(f.getLocationOnScreen().x + f.getSize().width,
                    f.getLocationOnScreen().y);
        }
    }

    public void ocultaPopA() {
        if (popAsigna != null) {
            if (popAsigna.isVisible()) {
                popAsigna.setVisible(false);
            }
        }
    }

    private void creaPop(JTextField f) {
        if (pop != null) {
            if (pop.isVisible()) {
                pop.setVisible(false);
            } else {
                pop = new JPopupMenu();
                tecladoNumerico = new JNumBoardPane(f);
                pop.add(tecladoNumerico);
                pop.setVisible(true);
                pop.setLocation(f.getLocationOnScreen().x + f.getSize().width, f.getLocationOnScreen().y);
            }
        } else {
            pop = new JPopupMenu();
            tecladoNumerico = new JNumBoardPane(f);
            pop.add(tecladoNumerico);
            pop.setVisible(true);
            pop.setLocation(f.getLocationOnScreen().x + f.getSize().width, f.getLocationOnScreen().y);
        }
    }

    public int ocultaPop(JTextField f, int l, int minimo, int maximo) {
        if (pop != null) {
            if (pop.isVisible()) {
                pop.setVisible(false);
            }
            int t = 0;
            try {
                t = Integer.parseInt(f.getText());
            } catch (Exception e) {
                f.setText("" + l);
                t = l;
            }
            if (t > maximo || t < minimo) {
                JOptionPane.showMessageDialog(null, "Valor fuera de rango\n El valor debe estar entre " + minimo + " a " + maximo, "Error", JOptionPane.ERROR_MESSAGE);
                f.setText("" + minimo);
                return minimo;
            } else {
                return t;
                //return Integer.parseInt(f.getText());
            }
        }
        return 0;
    }

    public void cambiaColor(JToggleButton b) {
        for (Bioreactor bio : Variables.bioreactores) {
            if (Variables.idBioreactor == bio.getId()) {
                if (b.isSelected()) {
                    b.setBackground(Color.green);
                    b.setOpaque(true);
                    for (int j = 0; j < bio.getBombasSize(); j++) {
                        if (b.getName().equals(Integer.toString(j + 1))) {
                            bio.getBomba(j).setEstadoControl(true);
                            bio.getBomba(j).setRunBomba(true);
                            //Variables.estadoControlBomba1 = true;
                            //Variables.runBomba1 = true;
                            Variables.añadirEvento("Activo modo manual Bomba peristaltica " + (j + 1) + " Bioreactor " + bio.getCapacidadLitros());
                        }
                    }
                } else {
                    b.setBackground(Color.red);
                    b.setOpaque(true);
                    System.out.println(b.getName());
                    for (int j = 0; j < bio.getBombasSize(); j++) {
                        if (b.getName().equals(Integer.toString(j + 1))) {
                            bio.getBomba(j).setEstadoControl(false);
                            bio.getBomba(j).setRunBomba(false);
                            //Variables.estadoControlBomba1 = false;
                            //Hardware.Activar("Bomba1", false);
                            //Variables.runBomba1 = false;
                            Variables.añadirEvento("Desactivo modo manual Bomba peristaltica " + (j + 1) + " Bioreactor " + bio.getId());
                        }
                    }
                }
            }
        }
    }

    private void bomba1OnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bomba1OnActionPerformed
        for (Bioreactor bio : Variables.bioreactores) {
            if (Variables.idBioreactor == bio.getId()) {
                if (!bio.getBomba(0).isRunBomba()) {
                    Variables.añadirEvento("Activo modo automatico Bomba peristaltica " + bio.getBomba(1) + " Bioreactor " + bio.getId());
                    bio.getBomba(0).setEstadoOn(true);
                    bomba1On.setBackground(Color.GREEN);
                    bomba1On.setOpaque(true);
                    bomba1Off.setBackground(Color.GRAY);
                    bomba1Off.setOpaque(true);
                    //Variables.estadoOn1 = true;
                } else {
                    JOptionPane.showMessageDialog(null, "Primero debe detener la bomba", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_bomba1OnActionPerformed

    private void bomba1OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bomba1OffActionPerformed
        for (Bioreactor bio : Variables.bioreactores) {
            if (Variables.idBioreactor == bio.getId()) {
                String asignacion = bio.getBomba(0).getParametros().getAsignacionBomba();

                if ((asignacion.equals("Acido") || asignacion.equals("Base")) && bio.isEstadoControlpH()) {
                    JOptionPane.showMessageDialog(null,
                            "Primero debe detener el control de pH",
                            "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    Variables.añadirEvento("Desactivo modo automatico Bomba peristaltica 1 Bioreactor " + bio.getId());
                    bio.getBomba(0).setEstadoOn(false);
                    bomba1On.setBackground(Color.GRAY);
                    bomba1On.setOpaque(true);
                    bomba1Off.setBackground(Color.RED);
                    bomba1Off.setOpaque(true);
                }
            }
        }
    }//GEN-LAST:event_bomba1OffActionPerformed

    private void runBomba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runBomba1ActionPerformed
        cambiaColor(runBomba1);
    }//GEN-LAST:event_runBomba1ActionPerformed

    private void SetPointBomba1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SetPointBomba1FocusGained
        if (Variables.rol.equals("Administrador")) {
            creaPop(SetPointBomba1);
        }
        focusGained = true;
    }//GEN-LAST:event_SetPointBomba1FocusGained

    private void SetPointBomba1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SetPointBomba1FocusLost
        if (Variables.rol.equals("Administrador")) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    bio.getBomba(0).setPorcentajeDuty(ocultaPop(SetPointBomba1, (int) bio.getBomba(0).getPorcentajeDuty(), 0, 100));
                    Variables.añadirEvento("Cambio Setpoint de Bomba 1 Biorreactor " + (bio.getId() - 100));
                }
            }
        }
        focusGained = false;
    }//GEN-LAST:event_SetPointBomba1FocusLost

    private void PeriodoBomba1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PeriodoBomba1FocusGained
        if (Variables.rol.equals("Administrador")) {
            creaPop(PeriodoBomba1);
        }
        focusGained = true;
    }//GEN-LAST:event_PeriodoBomba1FocusGained

    private void PeriodoBomba1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PeriodoBomba1FocusLost
        if (Variables.rol.equals("Administrador")) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    bio.getBomba(0).setTiempoEncendidoSegundos(ocultaPop(PeriodoBomba1, (int) bio.getBomba(0).getTiempoEncendidoSegundos(), 0, 60));
                    Variables.añadirEvento("Cambio Periodo de Bomba 1 Biorreactor " + (bio.getId() - 100));
                }
            }
        }
        focusGained = false;
    }//GEN-LAST:event_PeriodoBomba1FocusLost

    private void asignacionBomba1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_asignacionBomba1FocusGained
        if (Variables.rol.equals("Administrador")) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    //if (!Variables.runBomba1 && !Variables.estadoOn1) {
                    if (!bio.getBomba(0).isRunBomba() && !bio.getBomba(0).isEstadoOn()) {
                        creaPopA(asignacionBomba1);
                    }
                }
            }
        }
        focusGained = true;
    }//GEN-LAST:event_asignacionBomba1FocusGained

    private void asignacionBomba1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_asignacionBomba1FocusLost
        if (Variables.rol.equals("Administrador")) {
            ocultaPopA();
            String nuevaAsignacion = asignacionBomba1.getText().trim();

            for (Bioreactor bio : Variables.bioreactores) {
                if (bio.getId() == Variables.idBioreactor) {
                    if (!nuevaAsignacion.isEmpty() && !verificarAsignacionDuplicadaEnMismoBioreactor(bio, nuevaAsignacion, 0)) {
                        bio.getBomba(0).getParametros().setAsignacionBomba(nuevaAsignacion);
                        Variables.añadirEvento("Asigno en la bomba 1 " + nuevaAsignacion + " del Biorreactor " + (bio.getId() - 100));
                    } else {
                        asignacionBomba1.setText(bio.getBomba(0).getParametros().getAsignacionBomba());
                    }
                    break;
                }
            }
        }
        focusGained = false;
    }//GEN-LAST:event_asignacionBomba1FocusLost

    private void bomba2OnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bomba2OnActionPerformed
        for (Bioreactor bio : Variables.bioreactores) {
            if (Variables.idBioreactor == bio.getId()) {
                if (!bio.getBomba(1).isRunBomba()) {
                    Variables.añadirEvento("Activo modo automatico Bomba peristaltica " + bio.getBomba(1) + " Bioreactor " + bio.getId());
                    bio.getBomba(1).setEstadoOn(true);
                    bomba2On.setBackground(Color.GREEN);
                    bomba2On.setOpaque(true);
                    bomba2Off.setBackground(Color.GRAY);
                    bomba2Off.setOpaque(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Primero debe detener la bomba", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_bomba2OnActionPerformed

    private void bomba2OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bomba2OffActionPerformed
        if (Variables.rol.equals("Administrador")) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    String asignacion = bio.getBomba(1).getParametros().getAsignacionBomba();

                    if ((asignacion.equals("Acido") || asignacion.equals("Base")) && bio.isEstadoControlpH()) {
                        JOptionPane.showMessageDialog(null,
                                "Primero debe detener el control de pH",
                                "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        Variables.añadirEvento("Desactivo modo automatico Bomba peristaltica 2 Bioreactor " + bio.getId());
                        bio.getBomba(1).setEstadoOn(false);
                        bomba2On.setBackground(Color.GRAY);
                        bomba2On.setOpaque(true);
                        bomba2Off.setBackground(Color.RED);
                        bomba2Off.setOpaque(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_bomba2OffActionPerformed

    private void SetPointBomba2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SetPointBomba2FocusGained
        if (Variables.rol.equals("Administrador")) {
            creaPop(SetPointBomba2);
            focusGained = true;
        }
    }//GEN-LAST:event_SetPointBomba2FocusGained

    private void SetPointBomba2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SetPointBomba2FocusLost
        if (Variables.rol.equals("Administrador")) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    bio.getBomba(1).setPorcentajeDuty(ocultaPop(SetPointBomba2, (int) bio.getBomba(1).getPorcentajeDuty(), 0, 100));
                    Variables.añadirEvento("Cambio Setpoint de Bomba 2 Biorreactor " + (bio.getId() - 100));
                }
            }
        }
        focusGained = false;
    }//GEN-LAST:event_SetPointBomba2FocusLost

    private void PeriodoBomba2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PeriodoBomba2FocusGained
        if (Variables.rol.equals("Administrador")) {
            creaPop(PeriodoBomba2);
        }
        focusGained = true;
    }//GEN-LAST:event_PeriodoBomba2FocusGained

    private void PeriodoBomba2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PeriodoBomba2FocusLost
        if (Variables.rol.equals("Administrador")) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    bio.getBomba(1).setTiempoEncendidoSegundos(ocultaPop(PeriodoBomba2, (int) bio.getBomba(1).getTiempoEncendidoSegundos(), 0, 60));
                    Variables.añadirEvento("Cambio Periodo de Bomba 2 Biorreactor " + (bio.getId() - 100));
                }
            }
        }
        focusGained = false;
    }//GEN-LAST:event_PeriodoBomba2FocusLost

    private void runBomba2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runBomba2ActionPerformed
        cambiaColor(runBomba2);
    }//GEN-LAST:event_runBomba2ActionPerformed

    private void asignacionBomba2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_asignacionBomba2FocusGained
        if (Variables.rol.equals("Administrador")) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    //if (!Variables.runBomba1 && !Variables.estadoOn1) {
                    if (!bio.getBomba(1).isRunBomba() && !bio.getBomba(1).isEstadoOn()) {
                        creaPopA(asignacionBomba2);
                    }
                }
            }
        }
        focusGained = true;
    }//GEN-LAST:event_asignacionBomba2FocusGained

    private void asignacionBomba2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_asignacionBomba2FocusLost
        if (Variables.rol.equals("Administrador")) {
            ocultaPopA();
            String nuevaAsignacion = asignacionBomba2.getText().trim();

            for (Bioreactor bio : Variables.bioreactores) {
                if (bio.getId() == Variables.idBioreactor) {
                    if (!nuevaAsignacion.isEmpty() && !verificarAsignacionDuplicadaEnMismoBioreactor(bio, nuevaAsignacion, 1)) {
                        bio.getBomba(1).getParametros().setAsignacionBomba(nuevaAsignacion);
                        Variables.añadirEvento("Asigno en la bomba 1 " + nuevaAsignacion + " del Biorreactor " + (bio.getId() - 100));
                    } else {
                        asignacionBomba2.setText(bio.getBomba(1).getParametros().getAsignacionBomba());
                    }
                    break;
                }
            }
        }
        focusGained = false;
    }//GEN-LAST:event_asignacionBomba2FocusLost

    private void bomba3OnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bomba3OnActionPerformed
        for (Bioreactor bio : Variables.bioreactores) {
            if (Variables.idBioreactor == bio.getId()) {
                if (!bio.getBomba(2).isRunBomba()) {
                    Variables.añadirEvento("Activo modo automatico Bomba peristaltica " + bio.getBomba(1) + " Bioreactor " + bio.getId());
                    bio.getBomba(2).setEstadoOn(true);
                    bomba3On.setBackground(Color.GREEN);
                    bomba3On.setOpaque(true);
                    bomba3Off.setBackground(Color.GRAY);
                    bomba3Off.setOpaque(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Primero debe detener la bomba", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_bomba3OnActionPerformed

    private void bomba3OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bomba3OffActionPerformed
        if (Variables.rol.equals("Administrador")) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    String asignacion = bio.getBomba(2).getParametros().getAsignacionBomba();

                    if ((asignacion.equals("Acido") || asignacion.equals("Base")) && bio.isEstadoControlpH()) {
                        JOptionPane.showMessageDialog(null,
                                "Primero debe detener el control de pH",
                                "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        Variables.añadirEvento("Desactivo modo automatico Bomba peristaltica 3 Bioreactor " + bio.getId());
                        bio.getBomba(2).setEstadoOn(false);
                        bomba3On.setBackground(Color.GRAY);
                        bomba3On.setOpaque(true);
                        bomba3Off.setBackground(Color.RED);
                        bomba3Off.setOpaque(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_bomba3OffActionPerformed

    private void SetPointBomba3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SetPointBomba3FocusGained
        if (Variables.rol.equals("Administrador")) {
            creaPop(SetPointBomba3);
        }
        focusGained = true;
    }//GEN-LAST:event_SetPointBomba3FocusGained

    private void SetPointBomba3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SetPointBomba3FocusLost
        if (Variables.rol.equals("Administrador")) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    bio.getBomba(2).setPorcentajeDuty(ocultaPop(SetPointBomba3, (int) bio.getBomba(2).getPorcentajeDuty(), 0, 100));
                    Variables.añadirEvento("Cambio Setpoint de Bomba 3 Bioreactor " + (bio.getId() - 100));
                }
            }
        }
        focusGained = false;
    }//GEN-LAST:event_SetPointBomba3FocusLost

    private void PeriodoBomba3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PeriodoBomba3FocusGained
        if (Variables.rol.equals("Administrador")) {
            creaPop(PeriodoBomba3);
        }
        focusGained = true;
    }//GEN-LAST:event_PeriodoBomba3FocusGained

    private void PeriodoBomba3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PeriodoBomba3FocusLost
        if (Variables.rol.equals("Administrador")) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    bio.getBomba(2).setTiempoEncendidoSegundos(ocultaPop(PeriodoBomba3, (int) bio.getBomba(2).getTiempoEncendidoSegundos(), 0, 60));
                    Variables.añadirEvento("Cambio Periodo de Bomba 3 Biorreactor " + (bio.getId() - 100));
                }
            }
        }
        focusGained = false;
    }//GEN-LAST:event_PeriodoBomba3FocusLost

    private void runBomba3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runBomba3ActionPerformed
        cambiaColor(runBomba3);
    }//GEN-LAST:event_runBomba3ActionPerformed

    private void asignacionBomba3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_asignacionBomba3FocusGained
        if (Variables.rol.equals("Administrador")) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    //if (!Variables.runBomba1 && !Variables.estadoOn1) {
                    if (!bio.getBomba(2).isRunBomba() && !bio.getBomba(2).isEstadoOn()) {
                        creaPopA(asignacionBomba3);
                    }
                }
            }
        }
        focusGained = true;
    }//GEN-LAST:event_asignacionBomba3FocusGained

    private void asignacionBomba3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_asignacionBomba3FocusLost
        if (Variables.rol.equals("Administrador")) {
            ocultaPopA();
            String nuevaAsignacion = asignacionBomba3.getText().trim();

            for (Bioreactor bio : Variables.bioreactores) {
                if (bio.getId() == Variables.idBioreactor) {
                    if (!nuevaAsignacion.isEmpty() && !verificarAsignacionDuplicadaEnMismoBioreactor(bio, nuevaAsignacion, 2)) {
                        bio.getBomba(2).getParametros().setAsignacionBomba(nuevaAsignacion);
                        Variables.añadirEvento("Asigno en la bomba 1 " + nuevaAsignacion + " del Biorreactor " + (bio.getId() - 100));
                    } else {
                        asignacionBomba1.setText(bio.getBomba(2).getParametros().getAsignacionBomba());
                    }
                    break;
                }
            }
        }
        focusGained = false;
    }//GEN-LAST:event_asignacionBomba3FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Verifica si la asignación ya fue usada en otra bomba dentro del mismo
     * bioreactor.
     *
     * @param bio Bioreactor actual
     * @param nuevaAsignacion Texto del campo (ej: "Ácido")
     * @param indiceActual Índice de la bomba que está editando el usuario (0 a
     * 3)
     * @return true si hay duplicado, false si es válida
     */
    public static boolean verificarAsignacionDuplicadaEnMismoBioreactor(Bioreactor bio, String nuevaAsignacion, int indiceActual) {
        for (int i = 0; i < bio.getBombasSize(); i++) {
            if (i == indiceActual) {
                continue;
            }
            String asignacion = bio.getBomba(i).getParametros().getAsignacionBomba();
            if (nuevaAsignacion.equalsIgnoreCase(asignacion)) {
                JOptionPane.showMessageDialog(null,
                        "La etiqueta \"" + nuevaAsignacion + "\" ya está asignada en la bomba " + (i + 1)
                        + ".",
                        "Asignación duplicada",
                        JOptionPane.WARNING_MESSAGE);
                return true;
            }
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField PeriodoBomba1;
    public static javax.swing.JTextField PeriodoBomba2;
    public static javax.swing.JTextField PeriodoBomba3;
    public static javax.swing.JTextField SetPointBomba1;
    public static javax.swing.JTextField SetPointBomba2;
    public static javax.swing.JTextField SetPointBomba3;
    public static javax.swing.JTextField asignacionBomba1;
    public static javax.swing.JTextField asignacionBomba2;
    public static javax.swing.JTextField asignacionBomba3;
    public static javax.swing.JButton bomba1Off;
    public static javax.swing.JButton bomba1On;
    public static javax.swing.JButton bomba2Off;
    public static javax.swing.JButton bomba2On;
    public static javax.swing.JButton bomba3Off;
    public static javax.swing.JButton bomba3On;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JToggleButton runBomba1;
    public static javax.swing.JToggleButton runBomba2;
    public static javax.swing.JToggleButton runBomba3;
    // End of variables declaration//GEN-END:variables

}
