/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.views;

import com.control.Variables;
import com.keyboard.JNumBoardPane;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTextField;
import javax.swing.Timer;

/**
 *
 * @author JP Electronica
 */
public class CalibracionBomba extends javax.swing.JFrame {

    private static final long serialVersionUID = 01;
    private int tiempo = 15;
    private JNumBoardPane tecladoNumerico;
    private JPopupMenu pop;
    private DecimalFormat decimales2 = new DecimalFormat("0.0");
    private double calibracionBomba1 = 0;
    private double calibracionBomba2 = 0;
    private double calibracionBomba3 = 0;
    private double calibracionBomba4 = 0;
    
    private double calibracionBomba1_B2 = 0;
    private double calibracionBomba2_B2 = 0;
    private double calibracionBomba3_B2 = 0;
    private double calibracionBomba4_B2 = 0;
    
    private double calibracionBomba1_B3 = 0;
    private double calibracionBomba2_B3 = 0;
    private double calibracionBomba3_B3 = 0;
    private double calibracionBomba4_B3 = 0;

    /**
     * Creates new form CalibracionBomba
     */
    public CalibracionBomba() {
        initComponents();
        setLocationRelativeTo(null);
        tiempo = 15;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        segundos15 = new javax.swing.JButton();
        segundos30 = new javax.swing.JButton();
        segundos60 = new javax.swing.JButton();
        iniciar = new javax.swing.JButton();
        detener = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textoSet = new javax.swing.JTextField();
        set = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Calibración"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tiempo de encendido (Segundos)");

        segundos15.setText("15");
        segundos15.setPreferredSize(new java.awt.Dimension(100, 50));
        segundos15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segundos15ActionPerformed(evt);
            }
        });

        segundos30.setText("30");
        segundos30.setPreferredSize(new java.awt.Dimension(100, 50));
        segundos30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segundos30ActionPerformed(evt);
            }
        });

        segundos60.setText("60");
        segundos60.setPreferredSize(new java.awt.Dimension(100, 50));
        segundos60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segundos60ActionPerformed(evt);
            }
        });

        iniciar.setText("INICIAR");
        iniciar.setPreferredSize(new java.awt.Dimension(100, 50));
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });

        detener.setText("DETENER");
        detener.setPreferredSize(new java.awt.Dimension(100, 50));
        detener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detenerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(iniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(segundos15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(segundos30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(segundos60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(detener, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(segundos15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(segundos30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(segundos60, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detener, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 43, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Ingrese Volumen obtenido (mL)");

        textoSet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoSet.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoSet.setText("0");
        textoSet.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textoSetFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoSetFocusLost(evt);
            }
        });

        set.setText("SET");
        set.setPreferredSize(new java.awt.Dimension(100, 50));
        set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(textoSet, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(set, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoSet, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(set, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void segundos15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segundos15ActionPerformed
        tiempo = 15;
        segundos15.setOpaque(true);
        segundos15.setBackground(Color.green);
        segundos30.setBackground(Color.lightGray);
        segundos60.setBackground(Color.lightGray);
    }//GEN-LAST:event_segundos15ActionPerformed

    private void segundos30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segundos30ActionPerformed
        tiempo = 30;
        segundos30.setOpaque(true);
        segundos30.setBackground(Color.green);
        segundos15.setBackground(Color.lightGray);
        segundos60.setBackground(Color.lightGray);
    }//GEN-LAST:event_segundos30ActionPerformed

    private void segundos60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segundos60ActionPerformed
        tiempo = 60;
        segundos60.setOpaque(true);
        segundos60.setBackground(Color.green);
        segundos30.setBackground(Color.lightGray);
        segundos15.setBackground(Color.lightGray);
    }//GEN-LAST:event_segundos60ActionPerformed

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        iniciar.setOpaque(true);
        iniciar.setBackground(Color.green);
        Variables.runCalibra = false;
        timer.setDelay(tiempo * 1000);
        timer.start();
        iniciar.setEnabled(false);
    }//GEN-LAST:event_iniciarActionPerformed

    private void detenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detenerActionPerformed
        Variables.runCalibra = true;
        iniciar.setEnabled(true);
        timer.stop();/*
        if (Variables.calibraBomba1) {
            Hardware.Activar("Bomba1", false);
        }
        if (Variables.calibraBomba2) {
            Hardware.Activar("Bomba2", false);
        }
        if (Variables.calibraBomba3) {
            Hardware.Activar("Bomba3", false);
        }
        if (Variables.calibraBomba4) {
            Hardware.Activar("Bomba4", false);
        }*/
    }//GEN-LAST:event_detenerActionPerformed

    private void setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setActionPerformed
        try {
            iniciar.setEnabled(true);
            timer.stop();
           /* if (Variables.calibraBomba1) {
                Hardware.Activar("Bomba1", false);
            }
            if (Variables.calibraBomba2) {
                Hardware.Activar("Bomba2", false);
            }
            if (Variables.calibraBomba3) {
                Hardware.Activar("Bomba3", false);
            }
            if (Variables.calibraBomba4) {
                Hardware.Activar("Bomba4", false);
            }
            if (Variables.calibraBomba1) {
                Variables.calibracionBomba1 = Double.parseDouble(textoSet.getText()) / tiempo;
//                BombasPeristalticas.calibradoBomba1.setText("" + decimales2.format(Variables.calibracionBomba1));
                Variables.añadirEvento("Calibro bomba persitaltica 1");
            }
            if (Variables.calibraBomba2) {
                Variables.calibracionBomba2 = Double.parseDouble(textoSet.getText()) / tiempo;
//                BombasPeristalticas.calibradoBomba2.setText("" + decimales2.format(Variables.calibracionBomba2));
                Variables.añadirEvento("Calibro bomba persitaltica 2");
            }
            if (Variables.calibraBomba3) {
                Variables.calibracionBomba3 = Double.parseDouble(textoSet.getText()) / tiempo;
//                BombasPeristalticas.calibradoBomba3.setText("" + decimales2.format(Variables.calibracionBomba3));
                Variables.añadirEvento("Calibro bomba persitaltica 3");
            }
            if (Variables.calibraBomba4) {
                Variables.calibracionBomba4 = Double.parseDouble(textoSet.getText()) / tiempo;
                //BombasPeristalticas.calibradoBomba4.setText("" + decimales2.format(Variables.calibracionBomba4));
                Variables.añadirEvento("Calibro bomba persitaltica 4");
            }*/
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se puede");
        }
    }//GEN-LAST:event_setActionPerformed

    private void textoSetFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoSetFocusGained
        creaPop(textoSet);
    }//GEN-LAST:event_textoSetFocusGained

    private void textoSetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoSetFocusLost
        if (Variables.calibraBomba1) {
            calibracionBomba1 = ocultaPop(textoSet, calibracionBomba1, 0, 10000);
        }
        if (Variables.calibraBomba2) {
            calibracionBomba2 = ocultaPop(textoSet, calibracionBomba2, 0, 10000);
        }
        if (Variables.calibraBomba3) {
            calibracionBomba3 = ocultaPop(textoSet, calibracionBomba3, 0, 10000);
        }
        if (Variables.calibraBomba4) {
            calibracionBomba4 = ocultaPop(textoSet, calibracionBomba4, 0, 10000);
        }
    }//GEN-LAST:event_textoSetFocusLost

    private void creaPop(JTextField f) {
        if (pop != null) {
            if (pop.isVisible()) {
                pop.setVisible(false);
            } else {
                pop = new JPopupMenu();
                tecladoNumerico = new JNumBoardPane(f);
                pop.add(tecladoNumerico);
                pop.setVisible(true);
                pop.setLocation(f.getLocationOnScreen().x - f.getSize().width, f.getLocationOnScreen().y);
            }
        } else {
            pop = new JPopupMenu();
            tecladoNumerico = new JNumBoardPane(f);
            pop.add(tecladoNumerico);
            pop.setVisible(true);
            pop.setLocation(f.getLocationOnScreen().x - f.getSize().width, f.getLocationOnScreen().y);
        }
    }

    public double ocultaPop(JTextField f, double l, double minimo, double maximo) {
        pop.setVisible(false);
        double t = 0;
        try {
            t = Integer.parseInt(f.getText());
        } catch (Exception e) {
            f.setText("" + l);
            t = l;
        }
        if (t > maximo || t < minimo) {
            JOptionPane.showMessageDialog(null, "Valor fuera de rango\n El valor debe estar entre " + minimo + " a " + maximo, "Error", JOptionPane.ERROR_MESSAGE);
            f.setText("" + minimo);
            return minimo;
        } else {
            return Integer.parseInt(f.getText());
        }
    }

    @SuppressWarnings("StaticNonFinalUsedInInitialization")
    public Timer timer = new Timer(20, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent ae) {
            System.out.println("Entro Timer");
            /*if (!Variables.runCalibra) {
                if (Variables.calibraBomba1) {
                    Hardware.Activar("Bomba1", true);
                }
                if (Variables.calibraBomba2) {
                    Hardware.Activar("Bomba2", true);
                }
                if (Variables.calibraBomba3) {
                    Hardware.Activar("Bomba3", true);
                }
                if (Variables.calibraBomba4) {
                    Hardware.Activar("Bomba4", true);
                }
                Variables.runCalibra=true;
            } else {
                Variables.runCalibra = true;
                iniciar.setEnabled(true);
                timer.stop();
                if (Variables.calibraBomba1) {
                    Hardware.Activar("Bomba1", false);
                }
                if (Variables.calibraBomba2) {
                    Hardware.Activar("Bomba2", false);
                }
                if (Variables.calibraBomba3) {
                    Hardware.Activar("Bomba3", false);
                }
                if (Variables.calibraBomba4) {
                    Hardware.Activar("Bomba4", false);
                }
            }*/
        }
    });

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalibracionBomba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalibracionBomba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalibracionBomba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalibracionBomba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalibracionBomba().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton detener;
    private javax.swing.JButton iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton segundos15;
    private javax.swing.JButton segundos30;
    private javax.swing.JButton segundos60;
    private javax.swing.JButton set;
    private javax.swing.JTextField textoSet;
    // End of variables declaration//GEN-END:variables
}
