/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.views;

import com.control.AjustesOD;
import com.control.AjustespH;
import com.control.Variables;
import com.keyboard.JNumBoardPane;
import com.model.Bioreactor;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author JuanDavid
 */
public class Control extends javax.swing.JPanel {

    private static final long serialVersionUID = 01;
    boolean hayAcido = false;
    boolean hayBase = false;
    private JNumBoardPane tecladoNumerico;
    private JPopupMenu pop;

    /**
     * Creates new form Contro
     */
    public Control() {
        initComponents();
        this.setBackground(new Color(240, 240, 255));
        jPanel1.setBackground(Color.WHITE);
        InicioControlAgitacion.setBackground(Color.GREEN);
        InicioControlTemperatura.setBackground(Color.GREEN);
        InicioControlpH.setBackground(Color.GREEN);
        InicioControlOD.setBackground(Color.GREEN);
        //InicioTiempo.setBackground(Color.GREEN);
        // BotonBomba.setBackground(Color.LIGHT_GRAY);                        
        AjustesOD.jComboBox1.setSelectedIndex(Variables.tipogas);
        double initial = 0.5, min = 0.1, max = 1.0, increment = 0.1;
        SpinnerNumberModel model = new SpinnerNumberModel(initial, min, max, increment);
        AjustespH.DeadBand.setModel(model);
        initial = 1.0;
        min = 1.0;
        max = 20.0;
        increment = 1.0;
        SpinnerNumberModel model2 = new SpinnerNumberModel(initial, min, max, increment);

    }

    public static int setpointtemperatura = 0, setpointph = 0, setpointod = 0, setpointco2 = 0, setpointagitador = 0, setpointTiempo = 0, setpointEsterilizacion = 0;
    public static int setpointtemperatura2 = 0, setpointph2 = 0, setpointod2 = 0, setpointco22 = 0, setpointagitador2 = 0;
    public static int setpointPresion = 0, setpointHisteresis = 0;

    private void creaPop(JTextField f) {
        if (pop != null) {
            if (pop.isVisible()) {
                pop.setVisible(false);
            } else {
                pop = new JPopupMenu();
                tecladoNumerico = new JNumBoardPane(f);
                pop.add(tecladoNumerico);
                pop.setVisible(true);
                pop.setLocation(f.getLocationOnScreen().x + f.getSize().width, f.getLocationOnScreen().y);
            }
        } else {
            pop = new JPopupMenu();
            tecladoNumerico = new JNumBoardPane(f);
            pop.add(tecladoNumerico);
            pop.setVisible(true);
            pop.setLocation(f.getLocationOnScreen().x + f.getSize().width, f.getLocationOnScreen().y);
        }
    }

    public double ocultaPop(JTextField f, double l, double minimo, double maximo) {
        if (pop != null) {
            if (pop.isVisible()) {
                pop.setVisible(false);
            }
            double t = 0;
            try {
                t = Double.parseDouble(f.getText());
            } catch (Exception e) {
                f.setText("" + l);
                t = l;
            }
            if (t > maximo || t < minimo) {
                JOptionPane.showMessageDialog(null, "Valor fuera de rango\n El valor debe estar entre " + minimo + " a " + maximo, "Error", JOptionPane.ERROR_MESSAGE);
                f.setText("" + minimo);
                return minimo;
            } else {
                return t;
                //return Integer.parseInt(f.getText());
            }
        }
        return 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SetPointpH = new javax.swing.JTextField();
        PointValuepH = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        InicioControlpH = new javax.swing.JButton();
        SetPointAgitador = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        PointValueAgitador = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        InicioControlAgitacion = new javax.swing.JButton();
        InicioControlTemperatura = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        SetPointTemperatura = new javax.swing.JTextField();
        PointValueTemperatura = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        InicioControlOD = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        PointValueOD = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        SetPointHisteresis = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        SetPointEsterilizacion = new javax.swing.JTextField();
        InicioEsterilizacion = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        botonNivelAlto = new javax.swing.JButton();
        botonNivelMedio = new javax.swing.JButton();
        botonNivelBajo = new javax.swing.JButton();
        SetPointTiempo = new javax.swing.JTextField();
        PointValueEsteriliación1 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        PointValueCO2 = new javax.swing.JTextField();
        PointValueEsterilizacion = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        pointValuePresionCamara = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        pointValuePresionPrecamara = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        SetPointPresion = new javax.swing.JTextField();
        SetPointOD2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        InicioCO = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1280, 800));
        setMinimumSize(new java.awt.Dimension(1280, 800));
        setPreferredSize(new java.awt.Dimension(1280, 800));

        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 629));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 629));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 630));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(null);

        SetPointpH.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SetPointpH.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SetPointpH.setText("0");
        SetPointpH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SetPointpHFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SetPointpHFocusLost(evt);
            }
        });
        jPanel1.add(SetPointpH);
        SetPointpH.setBounds(960, 390, 108, 34);

        PointValuepH.setEditable(false);
        PointValuepH.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PointValuepH.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PointValuepH.setText("0.0");
        PointValuepH.setFocusable(false);
        jPanel1.add(PointValuepH);
        PointValuepH.setBounds(960, 430, 108, 34);

        jLabel32.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel32.setText("PV");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(940, 440, 16, 15);

        jLabel29.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel29.setText("SP");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(940, 400, 16, 15);

        jLabel33.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel33.setText("pH");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(1070, 400, 17, 15);

        jLabel34.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel34.setText("pH");
        jPanel1.add(jLabel34);
        jLabel34.setBounds(1070, 440, 17, 15);

        InicioControlpH.setText("Iniciar");
        InicioControlpH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioControlpHActionPerformed(evt);
            }
        });
        jPanel1.add(InicioControlpH);
        InicioControlpH.setBounds(1110, 390, 80, 75);

        SetPointAgitador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SetPointAgitador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SetPointAgitador.setText("0");
        SetPointAgitador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SetPointAgitadorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SetPointAgitadorFocusLost(evt);
            }
        });
        jPanel1.add(SetPointAgitador);
        SetPointAgitador.setBounds(960, 110, 108, 34);

        jLabel30.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel30.setText("PV");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(940, 160, 16, 15);

        PointValueAgitador.setEditable(false);
        PointValueAgitador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PointValueAgitador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PointValueAgitador.setText("0");
        PointValueAgitador.setFocusable(false);
        jPanel1.add(PointValueAgitador);
        PointValueAgitador.setBounds(960, 150, 108, 34);

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel10.setText("rpm");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(1070, 160, 25, 15);

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel9.setText("rpm");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(1070, 120, 25, 15);

        InicioControlAgitacion.setText("Iniciar");
        InicioControlAgitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioControlAgitacionActionPerformed(evt);
            }
        });
        jPanel1.add(InicioControlAgitacion);
        InicioControlAgitacion.setBounds(1110, 100, 75, 80);

        InicioControlTemperatura.setText("Iniciar");
        InicioControlTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioControlTemperaturaActionPerformed(evt);
            }
        });
        jPanel1.add(InicioControlTemperatura);
        InicioControlTemperatura.setBounds(1110, 520, 75, 80);

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel13.setText("°C");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(1070, 580, 13, 23);

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel12.setText("°C");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(1070, 540, 13, 23);

        SetPointTemperatura.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SetPointTemperatura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SetPointTemperatura.setText("0");
        SetPointTemperatura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SetPointTemperaturaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SetPointTemperaturaFocusLost(evt);
            }
        });
        jPanel1.add(SetPointTemperatura);
        SetPointTemperatura.setBounds(960, 530, 108, 34);

        PointValueTemperatura.setEditable(false);
        PointValueTemperatura.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PointValueTemperatura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PointValueTemperatura.setText("0");
        PointValueTemperatura.setFocusable(false);
        jPanel1.add(PointValueTemperatura);
        PointValueTemperatura.setBounds(960, 570, 108, 34);

        jLabel27.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel27.setText("PV");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(940, 580, 16, 15);

        jLabel25.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel25.setText("SP");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(940, 540, 16, 15);

        InicioControlOD.setText("Iniciar");
        InicioControlOD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioControlODActionPerformed(evt);
            }
        });
        jPanel1.add(InicioControlOD);
        InicioControlOD.setBounds(1110, 250, 80, 75);

        jLabel35.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel35.setText("%");
        jPanel1.add(jLabel35);
        jLabel35.setBounds(1070, 300, 9, 15);

        PointValueOD.setEditable(false);
        PointValueOD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PointValueOD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PointValueOD.setText("0.0");
        PointValueOD.setFocusable(false);
        jPanel1.add(PointValueOD);
        PointValueOD.setBounds(960, 290, 108, 34);

        jLabel37.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel37.setText("PV");
        jPanel1.add(jLabel37);
        jLabel37.setBounds(940, 300, 16, 15);

        jLabel31.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel31.setText("SP");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(940, 260, 16, 15);

        SetPointHisteresis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SetPointHisteresis.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SetPointHisteresis.setText("0");
        SetPointHisteresis.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SetPointHisteresisFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SetPointHisteresisFocusLost(evt);
            }
        });
        jPanel1.add(SetPointHisteresis);
        SetPointHisteresis.setBounds(220, 420, 108, 34);

        jLabel38.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel38.setText("%");
        jPanel1.add(jLabel38);
        jLabel38.setBounds(540, 550, 9, 15);

        jLabel36.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel36.setText("PV");
        jPanel1.add(jLabel36);
        jLabel36.setBounds(70, 210, 16, 15);

        SetPointEsterilizacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SetPointEsterilizacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SetPointEsterilizacion.setText("0");
        SetPointEsterilizacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SetPointEsterilizacionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SetPointEsterilizacionFocusLost(evt);
            }
        });
        jPanel1.add(SetPointEsterilizacion);
        SetPointEsterilizacion.setBounds(100, 160, 100, 34);

        InicioEsterilizacion.setText("Iniciar");
        InicioEsterilizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioEsterilizacionActionPerformed(evt);
            }
        });
        jPanel1.add(InicioEsterilizacion);
        InicioEsterilizacion.setBounds(180, 250, 70, 70);

        jLabel40.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel40.setText("PRESION");
        jPanel1.add(jLabel40);
        jLabel40.setBounds(120, 400, 55, 15);

        jLabel41.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel41.setText("HISTERESIS");
        jPanel1.add(jLabel41);
        jLabel41.setBounds(240, 400, 73, 15);
        jPanel1.add(botonNivelAlto);
        botonNivelAlto.setBounds(70, 550, 60, 40);
        jPanel1.add(botonNivelMedio);
        botonNivelMedio.setBounds(180, 550, 60, 40);
        jPanel1.add(botonNivelBajo);
        botonNivelBajo.setBounds(280, 550, 60, 40);

        SetPointTiempo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SetPointTiempo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SetPointTiempo.setText("0");
        SetPointTiempo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SetPointTiempoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SetPointTiempoFocusLost(evt);
            }
        });
        jPanel1.add(SetPointTiempo);
        SetPointTiempo.setBounds(220, 160, 108, 34);

        PointValueEsteriliación1.setEditable(false);
        PointValueEsteriliación1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PointValueEsteriliación1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PointValueEsteriliación1.setText("0.0");
        PointValueEsteriliación1.setFocusable(false);
        jPanel1.add(PointValueEsteriliación1);
        PointValueEsteriliación1.setBounds(220, 200, 108, 34);

        jLabel43.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel43.setText("TEMPERATURA");
        jPanel1.add(jLabel43);
        jLabel43.setBounds(100, 130, 110, 15);

        PointValueCO2.setEditable(false);
        PointValueCO2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PointValueCO2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PointValueCO2.setText("0.0");
        PointValueCO2.setFocusable(false);
        jPanel1.add(PointValueCO2);
        PointValueCO2.setBounds(420, 540, 108, 34);

        PointValueEsterilizacion.setEditable(false);
        PointValueEsterilizacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PointValueEsterilizacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PointValueEsterilizacion.setText("0.0");
        PointValueEsterilizacion.setFocusable(false);
        jPanel1.add(PointValueEsterilizacion);
        PointValueEsterilizacion.setBounds(100, 200, 100, 34);

        jLabel39.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel39.setText("SP");
        jPanel1.add(jLabel39);
        jLabel39.setBounds(70, 170, 16, 15);

        jLabel45.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel45.setText("PRECÁMARA");
        jPanel1.add(jLabel45);
        jLabel45.setBounds(690, 190, 80, 20);

        jLabel28.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel28.setText("SP");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(940, 120, 16, 15);

        jLabel42.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel42.setText("%");
        jPanel1.add(jLabel42);
        jLabel42.setBounds(1070, 260, 9, 15);

        jLabel47.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel47.setText("NIVEL CO2");
        jPanel1.add(jLabel47);
        jLabel47.setBounds(440, 580, 70, 20);

        jLabel48.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel48.setText("TIEMPO");
        jPanel1.add(jLabel48);
        jLabel48.setBounds(250, 130, 50, 15);

        pointValuePresionCamara.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        pointValuePresionCamara.setText("0.0");
        jPanel1.add(pointValuePresionCamara);
        pointValuePresionCamara.setBounds(520, 160, 50, 20);

        jLabel52.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel52.setText("kPa");
        jPanel1.add(jLabel52);
        jLabel52.setBounds(590, 170, 50, 10);

        pointValuePresionPrecamara.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        pointValuePresionPrecamara.setText("0.0");
        jPanel1.add(pointValuePresionPrecamara);
        pointValuePresionPrecamara.setBounds(690, 160, 50, 20);

        jLabel54.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel54.setText("kPa");
        jPanel1.add(jLabel54);
        jLabel54.setBounds(760, 170, 50, 10);

        jLabel49.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel49.setText("CÁMARA");
        jPanel1.add(jLabel49);
        jLabel49.setBounds(520, 190, 80, 20);

        SetPointPresion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SetPointPresion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SetPointPresion.setText("0");
        SetPointPresion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SetPointPresionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SetPointPresionFocusLost(evt);
            }
        });
        jPanel1.add(SetPointPresion);
        SetPointPresion.setBounds(90, 420, 108, 34);

        SetPointOD2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SetPointOD2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SetPointOD2.setText("0");
        SetPointOD2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SetPointOD2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SetPointOD2FocusLost(evt);
            }
        });
        jPanel1.add(SetPointOD2);
        SetPointOD2.setBounds(960, 250, 108, 34);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/symbol-check-icon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(960, 30, 65, 41);

        InicioCO.setText("Iniciar");
        InicioCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioCOActionPerformed(evt);
            }
        });
        jPanel1.add(InicioCO);
        InicioCO.setBounds(235, 350, 90, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void InicioControlODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioControlODActionPerformed

    }//GEN-LAST:event_InicioControlODActionPerformed

    private void InicioControlTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioControlTemperaturaActionPerformed
        if (Variables.usuario != null) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    if ("Iniciar".equals(InicioControlTemperatura.getText())) {
                        //if (Variables.valorTemperatura > 0 && Variables.valorTemperatura < 200) {
                        if (bio.leerEntrada(Bioreactor.Entrada.TEMPERATURA_1) > 0 && bio.leerEntrada(Bioreactor.Entrada.TEMPERATURA_1) < 200) {
                            Variables.añadirEvento("Inicio Control de Temperatura Bioreactor " + bio.getId());
                            InicioControlTemperatura.setText("Detener");
                            InicioControlTemperatura.setBackground(Color.RED);
                            bio.setEstadoControlTemperatura(true);
                            //Variables.Ganancia = Variables.Ganancia2;
                        } else {
                            JOptionPane.showMessageDialog(this, "Conecte el sensor de Temperatura");
                        }
                    } else {
                        Variables.añadirEvento("Detuvo Control de Temperatura Bioreactor " + bio.getId());
                        InicioControlTemperatura.setText("Iniciar");
                        InicioControlTemperatura.setBackground(Color.GREEN);
                        bio.setEstadoControlTemperatura(false);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe acceder con algun usuario");
        }
    }//GEN-LAST:event_InicioControlTemperaturaActionPerformed

    private void InicioControlAgitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioControlAgitacionActionPerformed
        if (Variables.usuario != null) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    if ("Iniciar".equals(InicioControlAgitacion.getText())) {
                        Variables.añadirEvento("Inicio Control de Agitación Bioreactor " + bio.getId());
                        InicioControlAgitacion.setText("Detener");
                        InicioControlAgitacion.setBackground(Color.RED);
                        bio.setEstadoControlAgitacion(true);
                    } else {
                        Variables.añadirEvento("Detuvo Control de Agitación Bioreactor " + bio.getId());
                        InicioControlAgitacion.setText("Iniciar");
                        InicioControlAgitacion.setBackground(Color.GREEN);
                        bio.setEstadoControlAgitacion(false);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe acceder con algun usuario");
        }
    }//GEN-LAST:event_InicioControlAgitacionActionPerformed

    private void InicioControlpHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioControlpHActionPerformed
        if (Variables.usuario != null) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    if ("Iniciar".equals(InicioControlpH.getText())) {
                        Variables.añadirEvento("Inicio Control de pH Bioreactor " + bio.getId());
                        for (int i = 0; i < bio.getBombasSize(); i++) {
                            String asignacion = bio.getBomba(i).getParametros().getAsignacionBomba();
                            boolean activa = bio.getBomba(i).isEstadoOn();

                            if ("Acido".equalsIgnoreCase(asignacion) && activa) {
                                hayAcido = true;
                            }
                            if ("Base".equalsIgnoreCase(asignacion) && activa) {
                                hayBase = true;
                            }
                        }
                        if (hayAcido && hayBase) {
                            InicioControlpH.setText("Detener");
                            InicioControlpH.setBackground(Color.RED);
                            bio.setEstadoControlpH(true);
                            // new Thread(new HiloPH()).start();
                        } else {
                            JOptionPane.showMessageDialog(this, "Asigne y active la bomba de Base y/o pH");
                        }
                    } else {
                        Variables.añadirEvento("Detuvo Control de pH Bioreactor " + bio.getId());
                        InicioControlpH.setText("Iniciar");
                        InicioControlpH.setBackground(Color.GREEN);
                        bio.setEstadoControlpH(false);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe acceder con algun usuario");
        }
    }//GEN-LAST:event_InicioControlpHActionPerformed

    private void SetPointEsterilizacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SetPointEsterilizacionFocusGained
        if (Variables.rol.equals("Administrador")) {
            creaPop(SetPointEsterilizacion);
        } else {
            /*
             SwingUtilities.invokeLater(new Runnable() {
             @Override
             public void run() {
             JOptionPane.showMessageDialog(null,
             "No esta autorizado para modificar este valor.",
             "Acceda como administrador",
             JOptionPane.WARNING_MESSAGE);
             SetPointEsterilizacion.transferFocus();
             }
             });*/
        }
    }//GEN-LAST:event_SetPointEsterilizacionFocusGained

    private void SetPointEsterilizacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SetPointEsterilizacionFocusLost
        for (Bioreactor bio : Variables.bioreactores) {
            if (Variables.idBioreactor == bio.getId()) {
                bio.getParametros().getEsterlizacion().setSetpoint(ocultaPop(SetPointEsterilizacion, bio.getParametros().getEsterlizacion().getSetpoint(), 105, 134));
                Variables.añadirEvento("Cambio Setpoint de Esterilizacion del Biorreactor " + (bio.getId() - 100) + " a " + bio.getParametros().getEsterlizacion().getSetpoint());
            }
        }
    }//GEN-LAST:event_SetPointEsterilizacionFocusLost

    private void SetPointTiempoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SetPointTiempoFocusGained
        if (Variables.rol.equals("Administrador")) {
            creaPop(SetPointTiempo);
        }
    }//GEN-LAST:event_SetPointTiempoFocusGained

    private void SetPointTiempoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SetPointTiempoFocusLost
        for (Bioreactor bio : Variables.bioreactores) {
            if (Variables.idBioreactor == bio.getId()) {
                bio.getParametros().getEsterlizacion().setTiempoMinutos((int) ocultaPop(SetPointTiempo, bio.getParametros().getEsterlizacion().getTiempoMinutos(), 1, 120));
                Variables.añadirEvento("Cambio Tiempo de Esterilizacion del Biorreactor " + (bio.getId() - 100) + " a " + bio.getParametros().getEsterlizacion().getTiempoMinutos());
            }
        }
    }//GEN-LAST:event_SetPointTiempoFocusLost

    private void SetPointAgitadorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SetPointAgitadorFocusGained
        if (Variables.rol.equals("Administrador")) {
            creaPop(SetPointAgitador);
        }
    }//GEN-LAST:event_SetPointAgitadorFocusGained

    private void SetPointAgitadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SetPointAgitadorFocusLost
        for (Bioreactor bio : Variables.bioreactores) {
            if (Variables.idBioreactor == bio.getId()) {
                bio.getParametros().getAgitacion().setSetpoint(ocultaPop(SetPointAgitador, bio.getParametros().getAgitacion().getSetpoint(), 0, 200));
                Variables.añadirEvento("Cambio Setpoint de Agitación del Biorreactor " + (bio.getId() - 100) + " a " + bio.getParametros().getAgitacion().getSetpoint());
            }
        }
    }//GEN-LAST:event_SetPointAgitadorFocusLost

    private void SetPointOD2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SetPointOD2FocusGained
        if (Variables.rol.equals("Administrador")) {
            creaPop(SetPointOD2);
        }
    }//GEN-LAST:event_SetPointOD2FocusGained

    private void SetPointOD2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SetPointOD2FocusLost
        for (Bioreactor bio : Variables.bioreactores) {
            if (Variables.idBioreactor == bio.getId()) {
                bio.getParametros().getOd().setSetpoint(ocultaPop(SetPointOD2, bio.getParametros().getOd().getSetpoint(), 0, 200));
                Variables.añadirEvento("Cambio Setpoint de OD del Biorreactor " + (bio.getId() - 100) + " a " + bio.getParametros().getOd().getSetpoint());
            }
        }
    }//GEN-LAST:event_SetPointOD2FocusLost

    private void SetPointpHFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SetPointpHFocusGained
        if (Variables.rol.equals("Administrador")) {
            creaPop(SetPointpH);
        }
    }//GEN-LAST:event_SetPointpHFocusGained

    private void SetPointpHFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SetPointpHFocusLost
        for (Bioreactor bio : Variables.bioreactores) {
            if (Variables.idBioreactor == bio.getId()) {
                bio.getParametros().getPh().setSetpoint(ocultaPop(SetPointpH, bio.getParametros().getPh().getSetpoint(), 0, 14));
                Variables.añadirEvento("Cambio Setpoint de pH del Biorreactor " + (bio.getId() - 100) + " a " + bio.getParametros().getPh().getSetpoint());
            }
        }
    }//GEN-LAST:event_SetPointpHFocusLost

    private void SetPointTemperaturaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SetPointTemperaturaFocusGained
        if (Variables.rol.equals("Administrador")) {
            creaPop(SetPointTemperatura);
        }
    }//GEN-LAST:event_SetPointTemperaturaFocusGained

    private void SetPointTemperaturaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SetPointTemperaturaFocusLost
        for (Bioreactor bio : Variables.bioreactores) {
            if (Variables.idBioreactor == bio.getId()) {
                bio.getParametros().getTemperatura().setSetpoint(ocultaPop(SetPointTemperatura, bio.getParametros().getTemperatura().getSetpoint(), 10, 100));
                Variables.añadirEvento("Cambio Setpoint de Temperatura del Biorreactor " + (bio.getId() - 100) + " a " + bio.getParametros().getTemperatura().getSetpoint());
            }
        }
    }//GEN-LAST:event_SetPointTemperaturaFocusLost

    private void SetPointPresionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SetPointPresionFocusGained
        if (Variables.rol.equals("Administrador")) {
            creaPop(SetPointPresion);
        }
    }//GEN-LAST:event_SetPointPresionFocusGained

    private void SetPointPresionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SetPointPresionFocusLost
        for (Bioreactor bio : Variables.bioreactores) {
            if (Variables.idBioreactor == bio.getId()) {
                bio.getParametros().getCO2().setSetpoint(ocultaPop(SetPointPresion, bio.getParametros().getCO2().getSetpoint(), 0, 200));
                Variables.añadirEvento("Cambio Setpoint de venteo del Biorreactor " + (bio.getId() - 100) + " a " + bio.getParametros().getPresion().getSetpoint());
            }
        }
    }//GEN-LAST:event_SetPointPresionFocusLost

    private void SetPointHisteresisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SetPointHisteresisFocusGained
        if (Variables.rol.equals("Administrador")) {
            creaPop(SetPointHisteresis);
        }
    }//GEN-LAST:event_SetPointHisteresisFocusGained

    private void SetPointHisteresisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SetPointHisteresisFocusLost
        for (Bioreactor bio : Variables.bioreactores) {
            if (Variables.idBioreactor == bio.getId()) {
                bio.getParametros().getCO2().setHisteresis(ocultaPop(SetPointHisteresis, bio.getParametros().getCO2().getHisteresis(), 0, 50));
                Variables.añadirEvento("Cambio Histeresis de venteo del Biorreactor " + (bio.getId() - 100) + " a " + bio.getParametros().getPresion().getSetpoint());
            }
        }
    }//GEN-LAST:event_SetPointHisteresisFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void InicioCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioCOActionPerformed
        if (Variables.usuario != null) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    if ("Iniciar".equals(InicioCO.getText())) {
                        Variables.añadirEvento("Inicio Control de venteo de CO2" + bio.getId());
                        InicioCO.setText("Detener");
                        InicioCO.setBackground(Color.RED);
                        bio.setEstadoControlCO2(true);

                    } else {
                        Variables.añadirEvento("Detuvo Control de Esterilización Bioreactor " + bio.getId());
                        InicioCO.setText("Iniciar");
                        InicioCO.setBackground(Color.GREEN);
                        bio.setEstadoControlCO2(false);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe acceder con algun usuario");
        }
    }//GEN-LAST:event_InicioCOActionPerformed

    private void InicioEsterilizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioEsterilizacionActionPerformed
        if (Variables.usuario != null) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    if ("Iniciar".equals(InicioEsterilizacion.getText())) {
                        //if (Variables.valorTemperatura > 0 && Variables.valorTemperatura < 200) {
                        if (bio.leerEntrada(Bioreactor.Entrada.TEMPERATURA_1) > 0 && bio.leerEntrada(Bioreactor.Entrada.TEMPERATURA_1) < 200) {
                            Variables.añadirEvento("Inicio Control de Esterilización Bioreactor " + bio.getId());
                            InicioEsterilizacion.setText("Detener");
                            InicioEsterilizacion.setBackground(Color.RED);
                            bio.setEstadoControlEsterilizacion(true);
                            //Variables.Ganancia = Variables.Ganancia2;
                        } else {
                            JOptionPane.showMessageDialog(this, "Conecte el sensor de Temperatura");
                        }
                    } else {
                        Variables.añadirEvento("Detuvo Control de Esterilización Bioreactor " + bio.getId());
                        InicioEsterilizacion.setText("Iniciar");
                        InicioEsterilizacion.setBackground(Color.GREEN);
                        bio.setEstadoControlEsterilizacion(false);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe acceder con algun usuario");
        }
    }//GEN-LAST:event_InicioEsterilizacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton InicioCO;
    public static javax.swing.JButton InicioControlAgitacion;
    public static javax.swing.JButton InicioControlOD;
    public static javax.swing.JButton InicioControlTemperatura;
    public static javax.swing.JButton InicioControlpH;
    public static javax.swing.JButton InicioEsterilizacion;
    public static javax.swing.JTextField PointValueAgitador;
    public static javax.swing.JTextField PointValueCO2;
    public static javax.swing.JTextField PointValueEsteriliación1;
    public static javax.swing.JTextField PointValueEsterilizacion;
    public static javax.swing.JTextField PointValueOD;
    public static javax.swing.JTextField PointValueTemperatura;
    public static javax.swing.JTextField PointValuepH;
    public static javax.swing.JTextField SetPointAgitador;
    public static javax.swing.JTextField SetPointEsterilizacion;
    public static javax.swing.JTextField SetPointHisteresis;
    public static javax.swing.JTextField SetPointOD2;
    public static javax.swing.JTextField SetPointPresion;
    public static javax.swing.JTextField SetPointTemperatura;
    public static javax.swing.JTextField SetPointTiempo;
    public static javax.swing.JTextField SetPointpH;
    public static javax.swing.JButton botonNivelAlto;
    public static javax.swing.JButton botonNivelBajo;
    public static javax.swing.JButton botonNivelMedio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel pointValuePresionCamara;
    public static javax.swing.JLabel pointValuePresionPrecamara;
    // End of variables declaration//GEN-END:variables
}
