/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.views;

import com.control.Variables;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Judapies
 */
public class Eventos extends javax.swing.JFrame {
    private static final long serialVersionUID = 01;
    /**
     * Creates new form TablaDatos
     */
    public static DefaultTableModel modelo2;
    
    public Eventos() {
        initComponents();
        setTitle("Eventos registrados");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/com/images/Logo JP2.png")).getImage());
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);        
        modelo2 = new DefaultTableModel();
        Tabla_Resultados.setModel(modelo2);
        Tabla_Resultados.setBackground(Color.white);
        String header[] = new String[] { "Fecha y Hora", "Usuario", "Evento"};
        modelo2.setColumnIdentifiers(header);
        cargaTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Resultados = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        EliminarEvento = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        EliminarTodos = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tabla_Resultados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Tabla_Resultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabla_Resultados);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Logo JP2.png"))); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu1.setText("Editar");
        jMenu1.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jMenu1.add(jSeparator1);

        EliminarEvento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EliminarEvento.setText("Eliminar evento");
        EliminarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarEventoActionPerformed(evt);
            }
        });
        jMenu1.add(EliminarEvento);
        jMenu1.add(jSeparator2);

        EliminarTodos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EliminarTodos.setText("Eliminar todos los eventos");
        EliminarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarTodosActionPerformed(evt);
            }
        });
        jMenu1.add(EliminarTodos);
        jMenu1.add(jSeparator3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void cambiarAnchoColumna(int columnIndex, int width) {
        TableColumn columna = Tabla_Resultados.getColumnModel().getColumn(columnIndex);
        columna.setPreferredWidth(width);
    }
    
    public static void cargaTabla(){
        cambiarAnchoColumna(0, 10);
        cambiarAnchoColumna(1, 10);
        String []VectorLectura;
        VectorLectura = new String[3];
        for (int i = modelo2.getRowCount()-1; i >= 0 ; i--) {
            modelo2.removeRow(i);
        }
        Tabla_Resultados.repaint();
        Tabla_Resultados.updateUI();
        Tabla_Resultados.removeAll();
        for (int i = 0; i < Variables.evento.size(); i++){            
            VectorLectura[0] = Variables.fechaEvento.get(i);
            VectorLectura[1] = Variables.usuarioEvento.get(i);        
            VectorLectura[2] = Variables.evento.get(i);
            Eventos.modelo2.addRow(VectorLectura);
        }
    }
        
    private void EliminarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarEventoActionPerformed
        if(Variables.rol.equals("Administrador")){
            if(Tabla_Resultados.getSelectedRow()!=-1){
                int continuar = JOptionPane.showConfirmDialog(this,"¿Esta seguro que desea eliminar el evento?"
                                                                    + "\n"+Variables.evento.get(Tabla_Resultados.getSelectedRow()));
                if(continuar == JOptionPane.YES_OPTION){//si se selecciona SI 
                    Variables.usuarioEvento.remove(Tabla_Resultados.getSelectedRow());
                    Variables.fechaEvento.remove(Tabla_Resultados.getSelectedRow());
                    Variables.evento.remove(Tabla_Resultados.getSelectedRow());
                    modelo2.removeRow(Tabla_Resultados.getSelectedRow());
                }
            }else{
                JOptionPane.showMessageDialog(this, "Seleccione un evento primero");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Debe acceder como administrador");
        }
    }//GEN-LAST:event_EliminarEventoActionPerformed

    private void EliminarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarTodosActionPerformed
        if(Variables.rol.equals("Administrador")){
            int continuar = JOptionPane.showConfirmDialog(this,"¿Esta seguro que desea eliminar todos los eventos?");
            if(continuar == JOptionPane.YES_OPTION){//si se selecciona SI 
                Variables.usuarioEvento.clear();
                Variables.fechaEvento.clear();
                Variables.evento.clear();
                for (int i = modelo2.getRowCount()-1; i >= 0 ; i--) {
                    modelo2.removeRow(i);
                }
                Tabla_Resultados.repaint();
                Tabla_Resultados.updateUI();
                Tabla_Resultados.removeAll();
                JOptionPane.showMessageDialog(this, "Eventos Eliminados");
                Variables.añadirEvento("Elimino todos los eventos");
                cargaTabla();
            }
        }else{
            JOptionPane.showMessageDialog(this, "Debe acceder como administrador");
        }
    }//GEN-LAST:event_EliminarTodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eventos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EliminarEvento;
    private javax.swing.JMenuItem EliminarTodos;
    public static javax.swing.JTable Tabla_Resultados;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
