/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.views;

import com.control.Variables;
import com.graphs.HiloGrafica;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Formatter;
import java.util.GregorianCalendar;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SpinnerNumberModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.math.plot.Plot2DPanel;

/**
 *
 * @author JuanDavid
 */
public class Monitor extends javax.swing.JPanel {

    private static final long serialVersionUID = 01;
    public static Plot2DPanel grafica2D = new Plot2DPanel("SOUTH");

    /**
     * Creates new form Monitor
     */
    public Monitor() {
        initComponents();
        jPanel1.setBackground(Color.WHITE);
        jPanel2.setBackground(Color.WHITE);
        if (Variables.SelecMinutos) {
            Minutos.setSelected(true);
        }
        if (Variables.SelecSegundos) {
            Segundos.setSelected(true);
        }
        jSpinner1.setValue(Variables.TMuestreo / 1000);
        int initial = 1, min = 1, max = 30, increment = 1;
        SpinnerNumberModel model = new SpinnerNumberModel(initial, min, max, increment);
        jSpinner1.setModel(model);
        jSpinner1.setValue(Variables.TMuestreo);
        if (Variables.estadoAdquisicion) {
            jButton1.setText("Detener Adquisición");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Grafica = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        Segundos = new javax.swing.JRadioButton();
        Minutos = new javax.swing.JRadioButton();
        BorraGrafica = new javax.swing.JButton();
        BotonCargaDatos = new javax.swing.JButton();
        BotonGuardaDatos = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1280, 629));
        setMinimumSize(new java.awt.Dimension(1280, 629));
        setPreferredSize(new java.awt.Dimension(1280, 629));

        jPanel1.setMaximumSize(new java.awt.Dimension(1024, 470));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 470));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 470));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Button-Play-icon (1).png"))); // NOI18N
        jButton1.setText("Iniciar Adquisición");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Excel-icon.png"))); // NOI18N
        jButton2.setText("Exportar Datos ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Grafica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Grafica.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Logo JP2.png"))); // NOI18N
        Grafica.setMaximumSize(new java.awt.Dimension(780, 450));
        Grafica.setMinimumSize(new java.awt.Dimension(780, 450));
        Grafica.setPreferredSize(new java.awt.Dimension(780, 450));
        Grafica.setVisible(true);

        javax.swing.GroupLayout GraficaLayout = new javax.swing.GroupLayout(Grafica.getContentPane());
        Grafica.getContentPane().setLayout(GraficaLayout);
        GraficaLayout.setHorizontalGroup(
            GraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1078, Short.MAX_VALUE)
        );
        GraficaLayout.setVerticalGroup(
            GraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tiempo de Muestreo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        jPanel2.setOpaque(false);

        jSpinner1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 50, 1));

        buttonGroup1.add(Segundos);
        Segundos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Segundos.setText("Segundos");
        Segundos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SegundosActionPerformed(evt);
            }
        });

        buttonGroup1.add(Minutos);
        Minutos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Minutos.setText("Minutos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Minutos, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Segundos))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(Segundos)
                .addGap(37, 37, 37)
                .addComponent(Minutos)
                .addGap(18, 18, 18)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        BorraGrafica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Actions-edit-clear-list-icon.png"))); // NOI18N
        BorraGrafica.setText("Borrar Grafica");
        BorraGrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorraGraficaActionPerformed(evt);
            }
        });

        BotonCargaDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Hopstarter-Soft-Scraps-File-Open.16.png"))); // NOI18N
        BotonCargaDatos.setText("Cargar Datos ");
        BotonCargaDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCargaDatosActionPerformed(evt);
            }
        });

        BotonGuardaDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Custom-Icon-Design-Flatastic-9-Save.16.png"))); // NOI18N
        BotonGuardaDatos.setText("Guardar Datos");
        BotonGuardaDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardaDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonCargaDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(BotonGuardaDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BorraGrafica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Grafica, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Grafica, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonGuardaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonCargaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BorraGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1270, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (Variables.estadoAdquisicion) {
            JOptionPane.showMessageDialog(null, "Detenga la adquisiciòn de datos", "JP", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (com.views.InterfazFermentador.tabla2.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "No Hay Datos para Exportar.", "JP", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            Calendar cal = new GregorianCalendar();
            int hora = cal.get(Calendar.HOUR_OF_DAY);
            int minuto = cal.get(Calendar.MINUTE);
            int segundo = cal.get(Calendar.SECOND);
            Formatter formato2H = new Formatter();  // Formato de la hora
            formato2H.format("%02d", hora);
            String hora2 = formato2H.toString();    // String de la hora dos cifras
            Formatter formato2M = new Formatter();
            formato2M.format("%02d", minuto);
            String minuto2 = formato2M.toString();  // String de minutos dos cifras
            Formatter formato2S = new Formatter();
            formato2S.format("%02d", segundo);
            String segundo2 = formato2S.toString(); // String de segundos dos cifras

            JFileChooser chooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo de Excel", "xls");
            chooser.setFileFilter(filter);
            chooser.setDialogTitle("Guardar Como");
            chooser.setMultiSelectionEnabled(false);
            chooser.setAcceptAllFileFilterUsed(false);

            String defaultFileName = "datos"+hora2+minuto2+segundo2+cal.get(Calendar.DAY_OF_MONTH)+"-"+cal.get(Calendar.MONTH)+"-"+cal.get(Calendar.YEAR);
            chooser.setSelectedFile(new File(defaultFileName));
            
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                ArrayList<JTable> tb = new ArrayList<>();
                ArrayList<String> nom = new ArrayList<>();
                tb.add(com.views.InterfazFermentador.tabla2);
                nom.add("Datos del Proceso");
                String file = chooser.getSelectedFile().toString().concat(".xls");
                try {
                    com.graphs.ExportarLectura e = new com.graphs.ExportarLectura(new File(file), tb, nom, Variables.IngresoDatos);
                    Variables.añadirEvento("Exporto Datos a excel");
                    if (e.export()) {
                    }

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Hubo un error " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if ("Iniciar Adquisición".equals(jButton1.getText())) {
            Variables.añadirEvento("Inicio Adquisición de Datos");
            if (Segundos.isSelected()) {
                Variables.TMuestreo = (int) jSpinner1.getValue() * 1000;
                Variables.SelecSegundos = true;
                Variables.SelecMinutos = false;
            }
            if (Minutos.isSelected()) {
                Variables.TMuestreo = (int) jSpinner1.getValue() * 1000;
                Variables.TMuestreo = Variables.TMuestreo * 60;
                Variables.SelecMinutos = true;
                Variables.SelecSegundos = false;
            }
            Variables.estadoAdquisicion = true;
            new Thread(new HiloGrafica()).start();
            jButton1.setText("Detener Adquisición");
        } else {
            Variables.añadirEvento("Detuvo Adquisición de Datos");
            Variables.estadoAdquisicion = false;
            jButton1.setText("Iniciar Adquisición");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void BorraGraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorraGraficaActionPerformed
        int continuar = JOptionPane.showConfirmDialog(null, "Se borrara la grafica"
                + "\n¿Desea continuar?");
        if (continuar == JOptionPane.YES_OPTION) {//si se selecciona SI 
            Variables.añadirEvento("Borro grafica de datos");
            int rowCount=com.views.InterfazFermentador.modelo2.getRowCount();            

            // Eliminar filas desde la última hasta la primera
            for (int i = rowCount - 1; i >= 0; i--) {
                com.views.InterfazFermentador.modelo2.removeRow(i);
            }
            com.graphs.Graficar.datosRedox.clear();
            com.graphs.Graficar.datosOD.clear();
            com.graphs.Graficar.datosPH.clear();
            com.graphs.Graficar.datosTemperatura.clear();
            com.graphs.Graficar.datosRPM.clear();
            com.graphs.Graficar.datosTiempo.clear();
            com.graphs.Graficar.n = 0;
            com.graphs.Graficar.tamaño = 0;
        }
    }//GEN-LAST:event_BorraGraficaActionPerformed

    private void SegundosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SegundosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SegundosActionPerformed

    private void BotonCargaDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCargaDatosActionPerformed
        if (Variables.estadoAdquisicion) {
            JOptionPane.showMessageDialog(null, "Detenga la adquisiciòn de datos", "JP", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JFileChooser chooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo JP", "jp");
            chooser.setFileFilter(filter);
            chooser.setDialogTitle("Abrir Archivo");
            chooser.setMultiSelectionEnabled(false);
            chooser.setAcceptAllFileFilterUsed(false);

            if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                ArrayList<JTable> tb = new ArrayList<>();
                String file = chooser.getSelectedFile().toString();
                System.out.println(file);
                File f = new File(file);
                if (f.exists()) {
                    com.info.AbrirArchivo o = new com.info.AbrirArchivo();
                    try {
                        o.openFile(f);
                    } catch (IOException | ClassNotFoundException ex) {
                        JOptionPane.showMessageDialog(null, "No puede abrir Info", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    try {
                        tb = o.fileConvert().get(0);
                        com.graphs.Graficar.graficar(tb);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, "No puede abrir Info", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }
    }//GEN-LAST:event_BotonCargaDatosActionPerformed

    private void BotonGuardaDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardaDatosActionPerformed
        if (Variables.estadoAdquisicion) {
            JOptionPane.showMessageDialog(null, "Detenga la adquisiciòn de datos", "JP", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (com.views.InterfazFermentador.tabla2.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "No Hay Datos para Guardar.", "JP", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            Calendar cal = new GregorianCalendar();
            int hora = cal.get(Calendar.HOUR_OF_DAY);
            int minuto = cal.get(Calendar.MINUTE);
            int segundo = cal.get(Calendar.SECOND);
            Formatter formato2H = new Formatter();  // Formato de la hora
            formato2H.format("%02d", hora);
            String hora2 = formato2H.toString();    // String de la hora dos cifras
            Formatter formato2M = new Formatter();
            formato2M.format("%02d", minuto);
            String minuto2 = formato2M.toString();  // String de minutos dos cifras
            Formatter formato2S = new Formatter();
            formato2S.format("%02d", segundo);
            String segundo2 = formato2S.toString(); // String de segundos dos cifras

            JFileChooser chooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo JP", "jp");
            chooser.setFileFilter(filter);
            chooser.setDialogTitle("Guardar Como");
            chooser.setMultiSelectionEnabled(false);
            chooser.setAcceptAllFileFilterUsed(false);
            String defaultFileName = "datos"+hora2+minuto2+segundo2+cal.get(Calendar.DAY_OF_MONTH)+"-"+cal.get(Calendar.MONTH)+"-"+cal.get(Calendar.YEAR);
            chooser.setSelectedFile(new File(defaultFileName));

            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                ArrayList<JTable> tb = new ArrayList<>();
                tb.add(com.views.InterfazFermentador.tabla2);
                com.info.GuardarArchivo s = new com.info.GuardarArchivo();
                String file = chooser.getSelectedFile().toString().concat(".jp");
                File f = new File(file);
                try {
                    s.startSaving(tb);
                    s.saveData(f);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "No puede guardar Datos", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_BotonGuardaDatosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BorraGrafica;
    private javax.swing.JButton BotonCargaDatos;
    private javax.swing.JButton BotonGuardaDatos;
    public static javax.swing.JInternalFrame Grafica;
    private javax.swing.JRadioButton Minutos;
    private javax.swing.JRadioButton Segundos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
