/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.views;

import com.control.Variables;
import com.model.Bioreactor;
import com.util.LabelUpdater;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author CCUCHIMBA
 */
public class TestComponentes extends javax.swing.JFrame {

    /**
     * Creates new form TestComponentes
     */
    @SuppressWarnings({"CallToThreadStartDuringObjectConstruction", "static-access", "OverridableMethodCallInConstructor"})
    public TestComponentes() {
        initComponents();
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/com/images/logo.png")).getImage());
        this.setLayout(null);
        setLocationRelativeTo(null);
        actualizaVisualizacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        AC1 = new javax.swing.JButton();
        AC2 = new javax.swing.JButton();
        AC3 = new javax.swing.JButton();
        AC4 = new javax.swing.JButton();
        AC5 = new javax.swing.JButton();
        AC6 = new javax.swing.JButton();
        AC7 = new javax.swing.JButton();
        AC8 = new javax.swing.JButton();
        AC9 = new javax.swing.JButton();
        AC10 = new javax.swing.JButton();
        AC11 = new javax.swing.JButton();
        AC12 = new javax.swing.JButton();
        SSR = new javax.swing.JButton();
        BOMBA1 = new javax.swing.JButton();
        BOMBA2 = new javax.swing.JButton();
        BOMBA3 = new javax.swing.JButton();
        AGITADOR = new javax.swing.JButton();
        BUZZER = new javax.swing.JButton();
        BIORREACTOR1 = new javax.swing.JButton();
        BIORREACTOR2 = new javax.swing.JButton();
        BIORREACTOR3 = new javax.swing.JButton();
        BIORREACTOR4 = new javax.swing.JButton();
        Off = new javax.swing.JButton();
        Temp1 = new javax.swing.JLabel();
        Temp2 = new javax.swing.JLabel();
        pH = new javax.swing.JLabel();
        OD = new javax.swing.JLabel();
        RPM_CH1 = new javax.swing.JLabel();
        RPM_CH2 = new javax.swing.JLabel();
        PresiónCámara = new javax.swing.JLabel();
        PresiónChaqueta = new javax.swing.JLabel();
        NivelAlto = new javax.swing.JLabel();
        NivelMedio = new javax.swing.JLabel();
        NivelBajo = new javax.swing.JLabel();
        CO2 = new javax.swing.JLabel();
        IN1 = new javax.swing.JLabel();
        IN2 = new javax.swing.JLabel();
        IN3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PointValueTemperatura = new javax.swing.JLabel();
        PointValueTemperatura2 = new javax.swing.JLabel();
        PointValuepH = new javax.swing.JLabel();
        PointValueOD = new javax.swing.JLabel();
        PointValueAgitador = new javax.swing.JLabel();
        PointValueRPMCH2 = new javax.swing.JLabel();
        PointValuePresionCamara = new javax.swing.JLabel();
        PointValuePresionPrecamara = new javax.swing.JLabel();
        botonNivelAlto = new javax.swing.JLabel();
        botonNivelMedio = new javax.swing.JLabel();
        botonNivelBajo = new javax.swing.JLabel();
        PointValueCO2 = new javax.swing.JLabel();
        PointValueIN1 = new javax.swing.JLabel();
        PointValueIN2 = new javax.swing.JLabel();
        tituloTest = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 800));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 800));
        setResizable(false);
        getContentPane().setLayout(null);

        AC1.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        AC1.setText("AC1");
        AC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AC1ActionPerformed(evt);
            }
        });
        getContentPane().add(AC1);
        AC1.setBounds(65, 281, 90, 90);

        AC2.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        AC2.setText("AC2");
        AC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AC2ActionPerformed(evt);
            }
        });
        getContentPane().add(AC2);
        AC2.setBounds(183, 281, 90, 90);

        AC3.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        AC3.setText("AC3");
        AC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AC3ActionPerformed(evt);
            }
        });
        getContentPane().add(AC3);
        AC3.setBounds(301, 281, 90, 90);

        AC4.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        AC4.setText("AC4");
        AC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AC4ActionPerformed(evt);
            }
        });
        getContentPane().add(AC4);
        AC4.setBounds(419, 281, 90, 90);

        AC5.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        AC5.setText("AC5");
        AC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AC5ActionPerformed(evt);
            }
        });
        getContentPane().add(AC5);
        AC5.setBounds(539, 281, 90, 90);

        AC6.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        AC6.setText("AC6");
        AC6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AC6ActionPerformed(evt);
            }
        });
        getContentPane().add(AC6);
        AC6.setBounds(657, 281, 90, 90);

        AC7.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        AC7.setText("AC7");
        AC7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AC7ActionPerformed(evt);
            }
        });
        getContentPane().add(AC7);
        AC7.setBounds(65, 405, 90, 90);

        AC8.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        AC8.setText("AC8");
        AC8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AC8ActionPerformed(evt);
            }
        });
        getContentPane().add(AC8);
        AC8.setBounds(183, 405, 90, 90);

        AC9.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        AC9.setText("AC9");
        AC9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AC9ActionPerformed(evt);
            }
        });
        getContentPane().add(AC9);
        AC9.setBounds(301, 405, 90, 90);

        AC10.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        AC10.setText("AC10");
        AC10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AC10ActionPerformed(evt);
            }
        });
        getContentPane().add(AC10);
        AC10.setBounds(419, 405, 90, 90);

        AC11.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        AC11.setText("AC11");
        AC11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AC11ActionPerformed(evt);
            }
        });
        getContentPane().add(AC11);
        AC11.setBounds(539, 405, 90, 90);

        AC12.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        AC12.setText("AC12");
        AC12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AC12ActionPerformed(evt);
            }
        });
        getContentPane().add(AC12);
        AC12.setBounds(657, 405, 90, 90);

        SSR.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        SSR.setText("SSR");
        SSR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSRActionPerformed(evt);
            }
        });
        getContentPane().add(SSR);
        SSR.setBounds(65, 529, 90, 90);

        BOMBA1.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        BOMBA1.setText("BOMBA1");
        BOMBA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOMBA1ActionPerformed(evt);
            }
        });
        getContentPane().add(BOMBA1);
        BOMBA1.setBounds(183, 529, 90, 90);

        BOMBA2.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        BOMBA2.setText("BOMBA2");
        BOMBA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOMBA2ActionPerformed(evt);
            }
        });
        getContentPane().add(BOMBA2);
        BOMBA2.setBounds(301, 529, 90, 90);

        BOMBA3.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        BOMBA3.setText("BOMBA3");
        BOMBA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOMBA3ActionPerformed(evt);
            }
        });
        getContentPane().add(BOMBA3);
        BOMBA3.setBounds(419, 529, 90, 90);

        AGITADOR.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        AGITADOR.setText("AGITADOR");
        AGITADOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGITADORActionPerformed(evt);
            }
        });
        getContentPane().add(AGITADOR);
        AGITADOR.setBounds(539, 529, 90, 90);

        BUZZER.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        BUZZER.setText("BUZZER");
        BUZZER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUZZERActionPerformed(evt);
            }
        });
        getContentPane().add(BUZZER);
        BUZZER.setBounds(657, 529, 90, 90);

        BIORREACTOR1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        BIORREACTOR1.setText("BIORREACTOR 1L");
        BIORREACTOR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIORREACTOR1ActionPerformed(evt);
            }
        });
        getContentPane().add(BIORREACTOR1);
        BIORREACTOR1.setBounds(260, 55, 141, 80);

        BIORREACTOR2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        BIORREACTOR2.setText("BIORREACTOR 5L");
        BIORREACTOR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIORREACTOR2ActionPerformed(evt);
            }
        });
        getContentPane().add(BIORREACTOR2);
        BIORREACTOR2.setBounds(531, 55, 143, 80);

        BIORREACTOR3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        BIORREACTOR3.setText("BIORREACTOR 30L");
        BIORREACTOR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIORREACTOR3ActionPerformed(evt);
            }
        });
        getContentPane().add(BIORREACTOR3);
        BIORREACTOR3.setBounds(753, 55, 151, 80);

        BIORREACTOR4.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        BIORREACTOR4.setText("BIORREACTOR 30L");
        BIORREACTOR4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIORREACTOR4ActionPerformed(evt);
            }
        });
        getContentPane().add(BIORREACTOR4);
        BIORREACTOR4.setBounds(1034, 55, 151, 80);

        Off.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/btn_regresar_azul_48x48.png"))); // NOI18N
        Off.setContentAreaFilled(false);
        Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OffActionPerformed(evt);
            }
        });
        getContentPane().add(Off);
        Off.setBounds(1100, 660, 56, 57);

        Temp1.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        Temp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/temperature-4-icon.png"))); // NOI18N
        Temp1.setText("Temp1");
        Temp1.setOpaque(true);
        getContentPane().add(Temp1);
        Temp1.setBounds(808, 304, 65, 20);

        Temp2.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        Temp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/temperature-4-icon.png"))); // NOI18N
        Temp2.setText("Temp2");
        Temp2.setOpaque(true);
        getContentPane().add(Temp2);
        Temp2.setBounds(808, 342, 68, 20);

        pH.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        pH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Pictogrammers-Material-Ph.16.png"))); // NOI18N
        pH.setText("pH");
        pH.setOpaque(true);
        getContentPane().add(pH);
        pH.setBounds(808, 380, 40, 20);

        OD.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        OD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8-water-steam-48.png"))); // NOI18N
        OD.setText("OD");
        OD.setOpaque(true);
        getContentPane().add(OD);
        OD.setBounds(808, 418, 41, 20);

        RPM_CH1.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        RPM_CH1.setText("RPM CH1");
        RPM_CH1.setOpaque(true);
        getContentPane().add(RPM_CH1);
        RPM_CH1.setBounds(808, 456, 62, 20);

        RPM_CH2.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        RPM_CH2.setText("RPM CH2");
        RPM_CH2.setOpaque(true);
        getContentPane().add(RPM_CH2);
        RPM_CH2.setBounds(808, 494, 65, 20);

        PresiónCámara.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        PresiónCámara.setText("Presión Cámara");
        PresiónCámara.setOpaque(true);
        getContentPane().add(PresiónCámara);
        PresiónCámara.setBounds(808, 532, 118, 20);

        PresiónChaqueta.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        PresiónChaqueta.setText("Presión Chaqueta");
        PresiónChaqueta.setOpaque(true);
        getContentPane().add(PresiónChaqueta);
        PresiónChaqueta.setBounds(808, 578, 129, 20);

        NivelAlto.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        NivelAlto.setText("Nivel Alto");
        NivelAlto.setOpaque(true);
        getContentPane().add(NivelAlto);
        NivelAlto.setBounds(1088, 304, 70, 20);

        NivelMedio.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        NivelMedio.setText("Nivel Medio");
        NivelMedio.setOpaque(true);
        getContentPane().add(NivelMedio);
        NivelMedio.setBounds(1088, 350, 84, 20);

        NivelBajo.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        NivelBajo.setText("Nivel bajo");
        NivelBajo.setOpaque(true);
        getContentPane().add(NivelBajo);
        NivelBajo.setBounds(1088, 388, 72, 20);

        CO2.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        CO2.setText("%CO2");
        CO2.setOpaque(true);
        getContentPane().add(CO2);
        CO2.setBounds(1088, 426, 39, 20);

        IN1.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        IN1.setText("IN1");
        IN1.setOpaque(true);
        getContentPane().add(IN1);
        IN1.setBounds(1088, 464, 20, 20);

        IN2.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        IN2.setText("IN2");
        IN2.setOpaque(true);
        getContentPane().add(IN2);
        IN2.setBounds(1088, 502, 23, 20);

        IN3.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        IN3.setText("IN3");
        IN3.setOpaque(true);
        getContentPane().add(IN3);
        IN3.setBounds(1088, 540, 23, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/LogoJPSinFondo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 630, 424, 141);

        PointValueTemperatura.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        PointValueTemperatura.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(PointValueTemperatura);
        PointValueTemperatura.setBounds(976, 309, 63, 20);

        PointValueTemperatura2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        PointValueTemperatura2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(PointValueTemperatura2);
        PointValueTemperatura2.setBounds(976, 347, 63, 20);

        PointValuepH.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        PointValuepH.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(PointValuepH);
        PointValuepH.setBounds(976, 385, 63, 20);

        PointValueOD.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        PointValueOD.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(PointValueOD);
        PointValueOD.setBounds(976, 418, 63, 20);

        PointValueAgitador.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        PointValueAgitador.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(PointValueAgitador);
        PointValueAgitador.setBounds(976, 461, 63, 20);

        PointValueRPMCH2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        PointValueRPMCH2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(PointValueRPMCH2);
        PointValueRPMCH2.setBounds(976, 499, 63, 20);

        PointValuePresionCamara.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        PointValuePresionCamara.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(PointValuePresionCamara);
        PointValuePresionCamara.setBounds(976, 537, 63, 20);

        PointValuePresionPrecamara.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        PointValuePresionPrecamara.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(PointValuePresionPrecamara);
        PointValuePresionPrecamara.setBounds(976, 583, 63, 20);

        botonNivelAlto.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        botonNivelAlto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(botonNivelAlto);
        botonNivelAlto.setBounds(1190, 309, 63, 20);

        botonNivelMedio.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        botonNivelMedio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(botonNivelMedio);
        botonNivelMedio.setBounds(1190, 355, 63, 20);

        botonNivelBajo.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        botonNivelBajo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(botonNivelBajo);
        botonNivelBajo.setBounds(1190, 390, 63, 20);

        PointValueCO2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        PointValueCO2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(PointValueCO2);
        PointValueCO2.setBounds(1190, 428, 63, 20);

        PointValueIN1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        PointValueIN1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(PointValueIN1);
        PointValueIN1.setBounds(1190, 467, 63, 20);

        PointValueIN2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        PointValueIN2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(PointValueIN2);
        PointValueIN2.setBounds(1190, 507, 63, 20);

        tituloTest.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        tituloTest.setText("SELECCIONE BIORREACTOR");
        getContentPane().add(tituloTest);
        tituloTest.setBounds(65, 178, 260, 21);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AC1ActionPerformed
        for (Bioreactor bio : Variables.bioreactores) {
            if (bio.getId() == Variables.idBioreactor) {
                bio.activarSalida(Bioreactor.Salida.SUMINISTRO_VAPOR,bio.leerSalida(Bioreactor.Salida.SUMINISTRO_VAPOR)==5?10:5);
                AC1.setBackground(bio.leerSalida(Bioreactor.Salida.SUMINISTRO_VAPOR)==5?Color.green:Color.red);
            }
        }
    }//GEN-LAST:event_AC1ActionPerformed

    private void AC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AC2ActionPerformed
        for (Bioreactor bio : Variables.bioreactores) {
            if (bio.getId() == Variables.idBioreactor) {
                bio.activarSalida(Bioreactor.Salida.RECIRCULACION,bio.leerSalida(Bioreactor.Salida.RECIRCULACION)==5?10:5);
                AC2.setBackground(bio.leerSalida(Bioreactor.Salida.RECIRCULACION)==5?Color.green:Color.red);
            }
        }
    }//GEN-LAST:event_AC2ActionPerformed

    private void AC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AC3ActionPerformed
        for (Bioreactor bio : Variables.bioreactores) {
            if (bio.getId() == Variables.idBioreactor) {
                bio.activarSalida(Bioreactor.Salida.ENTRADA_INTERCAMBIADOR,bio.leerSalida(Bioreactor.Salida.ENTRADA_INTERCAMBIADOR)==5?10:5);
                AC3.setBackground(bio.leerSalida(Bioreactor.Salida.ENTRADA_INTERCAMBIADOR)==5?Color.green:Color.red);
            }
        }
    }//GEN-LAST:event_AC3ActionPerformed

    private void AC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AC4ActionPerformed
        for (Bioreactor bio : Variables.bioreactores) {
            if (bio.getId() == Variables.idBioreactor) {
                bio.activarSalida(Bioreactor.Salida.SALIDA_INTERCAMBIADOR,bio.leerSalida(Bioreactor.Salida.SALIDA_INTERCAMBIADOR)==5?10:5);
                AC4.setBackground(bio.leerSalida(Bioreactor.Salida.SALIDA_INTERCAMBIADOR)==5?Color.green:Color.red);
            }
        }
    }//GEN-LAST:event_AC4ActionPerformed

    private void AC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AC5ActionPerformed
        for (Bioreactor bio : Variables.bioreactores) {
            if (bio.getId() == Variables.idBioreactor) {
                bio.activarSalida(Bioreactor.Salida.BOMBA_ENCARCELACION,bio.leerSalida(Bioreactor.Salida.BOMBA_ENCARCELACION)==5?10:5);
                AC5.setBackground(bio.leerSalida(Bioreactor.Salida.BOMBA_ENCARCELACION)==5?Color.green:Color.red);
            }
        }
    }//GEN-LAST:event_AC5ActionPerformed

    private void AC6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AC6ActionPerformed
        for (Bioreactor bio : Variables.bioreactores) {
            if (bio.getId() == Variables.idBioreactor) {
                bio.activarSalida(Bioreactor.Salida.DRENAJE,bio.leerSalida(Bioreactor.Salida.DRENAJE)==5?10:5);
                AC6.setBackground(bio.leerSalida(Bioreactor.Salida.DRENAJE)==5?Color.green:Color.red);
            }
        }
    }//GEN-LAST:event_AC6ActionPerformed

    private void AC7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AC7ActionPerformed
        for (Bioreactor bio : Variables.bioreactores) {
            if (bio.getId() == Variables.idBioreactor) {
                bio.activarSalida(Bioreactor.Salida.SUMINISTRO_AGUA_ENFRIAMIENTO,bio.leerSalida(Bioreactor.Salida.SUMINISTRO_AGUA_ENFRIAMIENTO)==5?10:5);
                AC7.setBackground(bio.leerSalida(Bioreactor.Salida.SUMINISTRO_AGUA_ENFRIAMIENTO)==5?Color.green:Color.red);
            }
        }
    }//GEN-LAST:event_AC7ActionPerformed

    private void AC8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AC8ActionPerformed
        for (Bioreactor bio : Variables.bioreactores) {
            if (bio.getId() == Variables.idBioreactor) {
                bio.activarSalida(Bioreactor.Salida.SALIDA_AGUA_ENFRIAMIENTO,bio.leerSalida(Bioreactor.Salida.SALIDA_AGUA_ENFRIAMIENTO)==5?10:5);
                AC8.setBackground(bio.leerSalida(Bioreactor.Salida.SALIDA_AGUA_ENFRIAMIENTO)==5?Color.green:Color.red);
            }
        }
    }//GEN-LAST:event_AC8ActionPerformed

    private void AC9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AC9ActionPerformed
        for (Bioreactor bio : Variables.bioreactores) {
            if (bio.getId() == Variables.idBioreactor) {
                bio.activarSalida(Bioreactor.Salida.BOMBA_RECIRCULACION,bio.leerSalida(Bioreactor.Salida.BOMBA_RECIRCULACION)==5?10:5);
                AC9.setBackground(bio.leerSalida(Bioreactor.Salida.BOMBA_RECIRCULACION)==5?Color.green:Color.red);
            }
        }
    }//GEN-LAST:event_AC9ActionPerformed

    private void AC10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AC10ActionPerformed
        for (Bioreactor bio : Variables.bioreactores) {
            if (bio.getId() == Variables.idBioreactor) {
                bio.activarSalida(Bioreactor.Salida.INGRESO_CO2,bio.leerSalida(Bioreactor.Salida.INGRESO_CO2)==5?10:5);
                AC10.setBackground(bio.leerSalida(Bioreactor.Salida.INGRESO_CO2)==5?Color.green:Color.red);
            }
        }
    }//GEN-LAST:event_AC10ActionPerformed

    private void AC11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AC11ActionPerformed
        for (Bioreactor bio : Variables.bioreactores) {
            if (bio.getId() == Variables.idBioreactor) {
                bio.activarSalida(Bioreactor.Salida.VENTEO_CO2,bio.leerSalida(Bioreactor.Salida.VENTEO_CO2)==5?10:5);
                AC11.setBackground(bio.leerSalida(Bioreactor.Salida.VENTEO_CO2)==5?Color.green:Color.red);
            }
        }
    }//GEN-LAST:event_AC11ActionPerformed

    private void AC12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AC12ActionPerformed
        for (Bioreactor bio : Variables.bioreactores) {
            if (bio.getId() == Variables.idBioreactor) {
                bio.activarSalida(Bioreactor.Salida.DESFOGUE_VAPOR,bio.leerSalida(Bioreactor.Salida.DESFOGUE_VAPOR)==5?10:5);
                AC12.setBackground(bio.leerSalida(Bioreactor.Salida.DESFOGUE_VAPOR)==5?Color.green:Color.red);
            }
        }
    }//GEN-LAST:event_AC12ActionPerformed

    private void SSRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSRActionPerformed
        for (Bioreactor bio : Variables.bioreactores) {
            if (bio.getId() == Variables.idBioreactor) {
                bio.activarSalida(Bioreactor.Salida.SSR,bio.leerSalida(Bioreactor.Salida.SSR)==5?10:5);
                SSR.setBackground(bio.leerSalida(Bioreactor.Salida.SSR)==5?Color.green:Color.red);
            }
        }
    }//GEN-LAST:event_SSRActionPerformed

    private void BOMBA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOMBA1ActionPerformed
        for (Bioreactor bio : Variables.bioreactores) {
            if (bio.getId() == Variables.idBioreactor) {
                bio.activarSalida(Bioreactor.Salida.BOMBA_PERISTALTICA_1,bio.leerSalida(Bioreactor.Salida.BOMBA_PERISTALTICA_1)==5?10:5);
                BOMBA1.setBackground(bio.leerSalida(Bioreactor.Salida.BOMBA_PERISTALTICA_1)==5?Color.green:Color.red);
            }
        }
    }//GEN-LAST:event_BOMBA1ActionPerformed

    private void BOMBA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOMBA2ActionPerformed
        for (Bioreactor bio : Variables.bioreactores) {
            if (bio.getId() == Variables.idBioreactor) {
                bio.activarSalida(Bioreactor.Salida.BOMBA_PERISTALTICA_2,bio.leerSalida(Bioreactor.Salida.BOMBA_PERISTALTICA_2)==5?10:5);
                BOMBA2.setBackground(bio.leerSalida(Bioreactor.Salida.BOMBA_PERISTALTICA_2)==5?Color.green:Color.red);
            }
        }
    }//GEN-LAST:event_BOMBA2ActionPerformed

    private void BOMBA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOMBA3ActionPerformed
        for (Bioreactor bio : Variables.bioreactores) {
            if (bio.getId() == Variables.idBioreactor) {
                bio.activarSalida(Bioreactor.Salida.BOMBA_PERISTALTICA_3,bio.leerSalida(Bioreactor.Salida.BOMBA_PERISTALTICA_3)==5?10:5);
                BOMBA3.setBackground(bio.leerSalida(Bioreactor.Salida.BOMBA_PERISTALTICA_3)==5?Color.green:Color.red);
            }
        }
    }//GEN-LAST:event_BOMBA3ActionPerformed

    private void AGITADORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGITADORActionPerformed
        for (Bioreactor bio : Variables.bioreactores) {
            if (bio.getId() == Variables.idBioreactor) {
                //bio.activarSalida(Bioreactor.Salida.,bio.leerSalida(Bioreactor.Salida.SSR)==5?10:5);
            }
        }
    }//GEN-LAST:event_AGITADORActionPerformed

    private void BUZZERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUZZERActionPerformed
        for (Bioreactor bio : Variables.bioreactores) {
            if (bio.getId() == Variables.idBioreactor) {
                bio.activarSalida(Bioreactor.Salida.BUZZER,bio.leerSalida(Bioreactor.Salida.BUZZER)==5?10:5);
                BUZZER.setBackground(bio.leerSalida(Bioreactor.Salida.BUZZER)==5?Color.green:Color.red);
            }
        }
    }//GEN-LAST:event_BUZZERActionPerformed

    private void BIORREACTOR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIORREACTOR1ActionPerformed
        Variables.idBioreactor=101;
        actualizaVisualizacion();
    }//GEN-LAST:event_BIORREACTOR1ActionPerformed

    private void BIORREACTOR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIORREACTOR2ActionPerformed
        Variables.idBioreactor=102;
        actualizaVisualizacion();
    }//GEN-LAST:event_BIORREACTOR2ActionPerformed

    private void BIORREACTOR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIORREACTOR3ActionPerformed
        Variables.idBioreactor=103;
        actualizaVisualizacion();
    }//GEN-LAST:event_BIORREACTOR3ActionPerformed

    private void BIORREACTOR4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIORREACTOR4ActionPerformed
        JOptionPane.showMessageDialog(null, "Biorreactor No disponible");
    }//GEN-LAST:event_BIORREACTOR4ActionPerformed

    private void OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OffActionPerformed
        //int continuar = JOptionPane.showConfirmDialog(null, "Se devolverá al menú principal"
        //    + "\n¿Desea continuar?");
        //if(continuar == JOptionPane.YES_OPTION){
        Variables.testComponentes=false;
        this.dispose();
        //}
    }//GEN-LAST:event_OffActionPerformed

    public void actualizaVisualizacion(){
        for (Bioreactor bio : Variables.bioreactores) {
            if (bio.getId() == Variables.idBioreactor) {
                tituloTest.setText(LabelUpdater.obtenerTextoDesdeBoton("BIORREACTOR", bio.getId()-100));
                AC1.setBackground(bio.leerSalida(Bioreactor.Salida.SUMINISTRO_VAPOR)==5?Color.green:Color.red);
                AC2.setBackground(bio.leerSalida(Bioreactor.Salida.RECIRCULACION)==5?Color.green:Color.red);
                AC3.setBackground(bio.leerSalida(Bioreactor.Salida.ENTRADA_INTERCAMBIADOR)==5?Color.green:Color.red);
                AC4.setBackground(bio.leerSalida(Bioreactor.Salida.SALIDA_INTERCAMBIADOR)==5?Color.green:Color.red);
                AC5.setBackground(bio.leerSalida(Bioreactor.Salida.BOMBA_ENCARCELACION)==5?Color.green:Color.red);
                AC6.setBackground(bio.leerSalida(Bioreactor.Salida.DRENAJE)==5?Color.green:Color.red);
                AC7.setBackground(bio.leerSalida(Bioreactor.Salida.SUMINISTRO_AGUA_ENFRIAMIENTO)==5?Color.green:Color.red);
                AC8.setBackground(bio.leerSalida(Bioreactor.Salida.SALIDA_AGUA_ENFRIAMIENTO)==5?Color.green:Color.red);
                AC9.setBackground(bio.leerSalida(Bioreactor.Salida.BOMBA_RECIRCULACION)==5?Color.green:Color.red);
                AC10.setBackground(bio.leerSalida(Bioreactor.Salida.INGRESO_CO2)==5?Color.green:Color.red);
                AC11.setBackground(bio.leerSalida(Bioreactor.Salida.VENTEO_CO2)==5?Color.green:Color.red);
                AC12.setBackground(bio.leerSalida(Bioreactor.Salida.DESFOGUE_VAPOR)==5?Color.green:Color.red);
                SSR.setBackground(bio.leerSalida(Bioreactor.Salida.SSR)==5?Color.green:Color.red);
                BOMBA1.setBackground(bio.leerSalida(Bioreactor.Salida.BOMBA_PERISTALTICA_1)==5?Color.green:Color.red);
                BOMBA2.setBackground(bio.leerSalida(Bioreactor.Salida.BOMBA_PERISTALTICA_2)==5?Color.green:Color.red);
                BOMBA3.setBackground(bio.leerSalida(Bioreactor.Salida.BOMBA_PERISTALTICA_3)==5?Color.green:Color.red);
                BUZZER.setBackground(bio.leerSalida(Bioreactor.Salida.BUZZER)==5?Color.green:Color.red);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestComponentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton AC1;
    public static javax.swing.JButton AC10;
    public static javax.swing.JButton AC11;
    public static javax.swing.JButton AC12;
    public static javax.swing.JButton AC2;
    public static javax.swing.JButton AC3;
    public static javax.swing.JButton AC4;
    public static javax.swing.JButton AC5;
    public static javax.swing.JButton AC6;
    public static javax.swing.JButton AC7;
    public static javax.swing.JButton AC8;
    public static javax.swing.JButton AC9;
    public static javax.swing.JButton AGITADOR;
    public static javax.swing.JButton BIORREACTOR1;
    public static javax.swing.JButton BIORREACTOR2;
    public static javax.swing.JButton BIORREACTOR3;
    public static javax.swing.JButton BIORREACTOR4;
    public static javax.swing.JButton BOMBA1;
    public static javax.swing.JButton BOMBA2;
    public static javax.swing.JButton BOMBA3;
    public static javax.swing.JButton BUZZER;
    private javax.swing.JLabel CO2;
    private javax.swing.JLabel IN1;
    private javax.swing.JLabel IN2;
    private javax.swing.JLabel IN3;
    private javax.swing.JLabel NivelAlto;
    private javax.swing.JLabel NivelBajo;
    private javax.swing.JLabel NivelMedio;
    private javax.swing.JLabel OD;
    private javax.swing.JButton Off;
    public static javax.swing.JLabel PointValueAgitador;
    public static javax.swing.JLabel PointValueCO2;
    public static javax.swing.JLabel PointValueIN1;
    public static javax.swing.JLabel PointValueIN2;
    public static javax.swing.JLabel PointValueOD;
    public static javax.swing.JLabel PointValuePresionCamara;
    public static javax.swing.JLabel PointValuePresionPrecamara;
    public static javax.swing.JLabel PointValueRPMCH2;
    public static javax.swing.JLabel PointValueTemperatura;
    public static javax.swing.JLabel PointValueTemperatura2;
    public static javax.swing.JLabel PointValuepH;
    private javax.swing.JLabel PresiónChaqueta;
    private javax.swing.JLabel PresiónCámara;
    private javax.swing.JLabel RPM_CH1;
    private javax.swing.JLabel RPM_CH2;
    public static javax.swing.JButton SSR;
    private javax.swing.JLabel Temp1;
    private javax.swing.JLabel Temp2;
    public static javax.swing.JLabel botonNivelAlto;
    public static javax.swing.JLabel botonNivelBajo;
    public static javax.swing.JLabel botonNivelMedio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel pH;
    public static javax.swing.JLabel tituloTest;
    // End of variables declaration//GEN-END:variables
}
