/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.views;

import com.control.Variables;
import java.awt.Color;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Judapies
 */
public class Usuarios extends javax.swing.JFrame {
    private static final long serialVersionUID = 01;
    /**
     * Creates new form TablaDatos
     */
    public static DefaultTableModel modelo2;
    
    public Usuarios() {
        initComponents();
        setTitle("Usuarios");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/com/images/Logo JP2.png")).getImage());
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);        
        modelo2 = new DefaultTableModel();
        Tabla_Resultados.setModel(modelo2);
        Tabla_Resultados.setBackground(Color.white);
        String header[] = new String[] { "Hora y Fecha de Creación", "Usuario", "Rol"};
        modelo2.setColumnIdentifiers(header);
        cargaTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Resultados = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        AñadirUsuario = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        EliminarUsuario = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        CambiarClave = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tabla_Resultados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tabla_Resultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabla_Resultados);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Logo JP2.png"))); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu1.setText("Editar");
        jMenu1.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N

        AñadirUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AñadirUsuario.setText("Añadir usuario");
        AñadirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(AñadirUsuario);
        jMenu1.add(jSeparator1);

        EliminarUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EliminarUsuario.setText("Eliminar usuario");
        EliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(EliminarUsuario);
        jMenu1.add(jSeparator2);

        CambiarClave.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CambiarClave.setText("Cambiar clave");
        CambiarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiarClaveActionPerformed(evt);
            }
        });
        jMenu1.add(CambiarClave);
        jMenu1.add(jSeparator3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargaTabla(){
        String []VectorLectura;
        VectorLectura = new String[10];
        for (int i = 0; i < Variables.usuarios.size(); i++) {
            VectorLectura[0] = Variables.fechas.get(i);
            VectorLectura[1] = Variables.usuarios.get(i);
            VectorLectura[2] = Variables.roles.get(i);
            Usuarios.modelo2.addRow(VectorLectura);
        }
    }
    public Object GetData(JTable table, int row_index, int col_index){
        return table.getModel().getValueAt(row_index, col_index);
    }
    private void AñadirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirUsuarioActionPerformed
        com.views.SignUp sg = new SignUp();
        sg.setVisible(true);
    }//GEN-LAST:event_AñadirUsuarioActionPerformed
    
    
    private void EliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUsuarioActionPerformed
        if(Tabla_Resultados.getSelectedRow()!=-1){
            int continuar = JOptionPane.showConfirmDialog(this,"¿Esta seguro que desea eliminar el usuario?"
                                                                + "\n"+Variables.usuarios.get(Tabla_Resultados.getSelectedRow()));
            if(continuar == JOptionPane.YES_OPTION){//si se selecciona SI 
                Variables.usuarios.remove(Tabla_Resultados.getSelectedRow());
                Variables.claves.remove(Tabla_Resultados.getSelectedRow());
                Variables.fechas.remove(Tabla_Resultados.getSelectedRow());
                Variables.roles.remove(Tabla_Resultados.getSelectedRow());
                modelo2.removeRow(Tabla_Resultados.getSelectedRow());
            }
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione un usuario primero");
        }
    }//GEN-LAST:event_EliminarUsuarioActionPerformed

    private void CambiarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiarClaveActionPerformed
        if(Tabla_Resultados.getSelectedRow()!=-1){
            CambioClave cc = new CambioClave();
            cc.setPosicionUsuario(Tabla_Resultados.getSelectedRow());
            cc.setTitle("Cambio de Clave del usuario "+Variables.usuarios.get(Tabla_Resultados.getSelectedRow()));
            cc.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione un usuario primero");
        }
    }//GEN-LAST:event_CambiarClaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AñadirUsuario;
    private javax.swing.JMenuItem CambiarClave;
    private javax.swing.JMenuItem EliminarUsuario;
    public static javax.swing.JTable Tabla_Resultados;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
