/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.control;

import com.keyboard.JNumBoardPane;
import com.model.Bioreactor;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;

/**
 *
 * @author Fermentador 7 Litros
 */
public class AjustesEsterilizacion extends javax.swing.JFrame {

    private static final long serialVersionUID = 01;
    JPopupMenu pop;
    JNumBoardPane teclado;
    public int limite = 4;

    /**
     * Creates new form AjustesControlTemperatura
     */
    public AjustesEsterilizacion() {
        initComponents();
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/com/images/logo.png")).getImage());
        for (Bioreactor bio : Variables.bioreactores) {
            if (Variables.idBioreactor == bio.getId()) {
                textoI.setText("" + bio.getParametros().getEsterlizacion().getIntegral());
                textoD.setText("" + bio.getParametros().getEsterlizacion().getDerivativo());
                jTextField2.setText("" + bio.getParametros().getEsterlizacion().getGanancia2());
                jTextField3.setText("" + bio.getParametros().getEsterlizacion().getTCiclo());
                tPulsosPurga.setText("" + bio.getParametros().getEsterlizacion().getPulsosPurga());
                Tpurga.setText("" + bio.getParametros().getEsterlizacion().getTPurga());
                Histeresis.setText("" + bio.getParametros().getEsterlizacion().getHisteresis());
                Tdesvio.setText("" + bio.getParametros().getEsterlizacion().getDesvio());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Accept = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Tpurga = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tPulsosPurga = new javax.swing.JTextField();
        Tdesvio = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Histeresis = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textoD = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        textoI = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JP-Biolab  Fermentors & Bioreactors");
        setAlwaysOnTop(true);
        setResizable(false);

        jPanel1.setFocusable(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/LogoJPSinFondo.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);

        Accept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/symbol-check-icon.png"))); // NOI18N
        Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptActionPerformed(evt);
            }
        });

        Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/delete-icon.png"))); // NOI18N
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajustes Control de Esterilización"));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Temperatura de purga:");

        Tpurga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tpurga.setText("0");
        Tpurga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TpurgaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TpurgaFocusLost(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("°C");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Pulsos Purga:");

        tPulsosPurga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tPulsosPurga.setText("0");
        tPulsosPurga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tPulsosPurgaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tPulsosPurgaFocusLost(evt);
            }
        });

        Tdesvio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tdesvio.setText("0");
        Tdesvio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TdesvioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TdesvioFocusLost(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("°C");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Desvio:");

        Histeresis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Histeresis.setText("0");
        Histeresis.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                HisteresisFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                HisteresisFocusLost(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Histeresis:");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("°C");

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.setText("0");
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Ganancia:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("D:");

        textoD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoD.setText("0");
        textoD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textoDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoDFocusLost(evt);
            }
        });

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField3.setText("0");
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("T. Ciclo:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("I:");

        textoI.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoI.setText("0");
        textoI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textoIFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoIFocusLost(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(4, 4, 4)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel7)
                        .add(8, 8, 8)
                        .add(Tpurga, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(9, 9, 9)
                        .add(jLabel17)
                        .add(17, 17, 17)
                        .add(jLabel8)
                        .add(13, 13, 13)
                        .add(tPulsosPurga, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(48, 48, 48)
                        .add(jLabel2)
                        .add(18, 18, 18)
                        .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jLabel21)
                                .add(132, 132, 132)
                                .add(Tdesvio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(9, 9, 9)
                                .add(jLabel20))
                            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .add(jLabel3)
                                    .add(143, 143, 143))
                                .add(jPanel2Layout.createSequentialGroup()
                                    .add(117, 117, 117)
                                    .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(17, 17, 17)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(textoI, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jLabel22)
                                .add(40, 40, 40)
                                .add(Histeresis, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(19, 19, 19)
                        .add(jLabel23)
                        .add(18, 18, 18)
                        .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 86, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(textoD, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(14, 14, 14)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel7)
                    .add(Tpurga, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(jLabel17))
                    .add(jLabel8)
                    .add(tPulsosPurga, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                        .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel2)))
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(9, 9, 9)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel21)
                            .add(Tdesvio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel22)
                            .add(Histeresis, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(10, 10, 10)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel20)
                                    .add(jLabel23)))))
                    .add(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel9)
                            .add(textoD, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(18, 18, 18)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                        .add(jLabel3)
                        .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel10)
                        .add(textoI, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jSeparator1)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(123, 123, 123)
                                .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 707, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(242, 242, 242)
                                .add(Accept, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 103, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(214, 214, 214)
                                .add(Cancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 103, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(7, 7, 7)
                .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 12, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(Accept, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Cancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptActionPerformed
        try {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    bio.getParametros().getEsterlizacion().setGanancia2(Double.parseDouble(jTextField2.getText()));
                    bio.getParametros().getEsterlizacion().setTCiclo(Double.parseDouble(jTextField3.getText()));
                    bio.getParametros().getEsterlizacion().setIntegral(Double.parseDouble(textoI.getText()));
                    bio.getParametros().getEsterlizacion().setDerivativo(Double.parseDouble(textoD.getText()));
                    bio.getParametros().getEsterlizacion().setTPurga(Double.parseDouble(Tpurga.getText()));
                    bio.getParametros().getEsterlizacion().setDesvio(Double.parseDouble(Tdesvio.getText()));
                    bio.getParametros().getEsterlizacion().setHisteresis(Double.parseDouble(Histeresis.getText()));
                    bio.getParametros().getEsterlizacion().setPulsosPurga(Integer.parseInt(tPulsosPurga.getText()));
                }
            }
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }
    }//GEN-LAST:event_AcceptActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void TpurgaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TpurgaFocusGained
        Tpurga.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(Tpurga);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(Tpurga.getLocationOnScreen().x + Tpurga.getSize().width, Tpurga.getLocationOnScreen().y);
    }//GEN-LAST:event_TpurgaFocusGained

    private void TpurgaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TpurgaFocusLost
        pop.setVisible(false);
        try {
            Double.parseDouble(Tpurga.getText());
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    Tpurga.setText("" + bio.getParametros().getEsterlizacion().getTPurga());
                }
            }
        }
    }//GEN-LAST:event_TpurgaFocusLost

    private void tPulsosPurgaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tPulsosPurgaFocusGained
        tPulsosPurga.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(tPulsosPurga);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(tPulsosPurga.getLocationOnScreen().x + tPulsosPurga.getSize().width, tPulsosPurga.getLocationOnScreen().y);
    }//GEN-LAST:event_tPulsosPurgaFocusGained

    private void tPulsosPurgaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tPulsosPurgaFocusLost
        pop.setVisible(false);
        try {
            Integer.parseInt(tPulsosPurga.getText());
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    tPulsosPurga.setText("" + bio.getParametros().getEsterlizacion().getPulsosPurga());
                }
            }
        }
    }//GEN-LAST:event_tPulsosPurgaFocusLost

    private void TdesvioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TdesvioFocusGained
        Tdesvio.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(Tdesvio);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(Tdesvio.getLocationOnScreen().x + Tdesvio.getSize().width, Tdesvio.getLocationOnScreen().y);
    }//GEN-LAST:event_TdesvioFocusGained

    private void TdesvioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TdesvioFocusLost
        pop.setVisible(false);
        try {
            Double.parseDouble(Tdesvio.getText());
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    Tdesvio.setText("" + bio.getParametros().getEsterlizacion().getDesvio());
                }
            }
        }
    }//GEN-LAST:event_TdesvioFocusLost

    private void HisteresisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_HisteresisFocusGained
        Histeresis.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(Histeresis);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(Histeresis.getLocationOnScreen().x + Histeresis.getSize().width, Histeresis.getLocationOnScreen().y);
    }//GEN-LAST:event_HisteresisFocusGained

    private void HisteresisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_HisteresisFocusLost
        pop.setVisible(false);
        try {
            Double.parseDouble(Histeresis.getText());
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    Histeresis.setText("" + bio.getParametros().getEsterlizacion().getDesvio());
                }
            }
        }
    }//GEN-LAST:event_HisteresisFocusLost

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        jTextField2.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(jTextField2);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(jTextField2.getLocationOnScreen().x + jTextField2.getSize().width, jTextField2.getLocationOnScreen().y);
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        pop.setVisible(false);
        try {
            jTextField2.setText("" + Integer.parseInt(jTextField2.getText()));
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    jTextField2.setText("" + bio.getParametros().getEsterlizacion().getGanancia2());
                }
            }
        }
    }//GEN-LAST:event_jTextField2FocusLost

    private void textoDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoDFocusGained
        textoD.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(textoD);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(textoD.getLocationOnScreen().x + textoD.getSize().width, textoD.getLocationOnScreen().y);
    }//GEN-LAST:event_textoDFocusGained

    private void textoDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoDFocusLost
        pop.setVisible(false);
        try {
            textoD.setText(""+Double.parseDouble(textoD.getText()));
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    textoD.setText("" + bio.getParametros().getEsterlizacion().getDerivativo());
                }
            }
        }
    }//GEN-LAST:event_textoDFocusLost

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
        jTextField3.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(jTextField3);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(jTextField3.getLocationOnScreen().x + jTextField3.getSize().width, jTextField3.getLocationOnScreen().y);
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        pop.setVisible(false);
        try {
            jTextField3.setText("" + Integer.parseInt(jTextField3.getText()));
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    jTextField3.setText("" + bio.getParametros().getEsterlizacion().getTCiclo());
                }
            }
        }
    }//GEN-LAST:event_jTextField3FocusLost

    private void textoIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoIFocusGained
        textoI.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(textoI);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(textoI.getLocationOnScreen().x + textoI.getSize().width, textoI.getLocationOnScreen().y);
    }//GEN-LAST:event_textoIFocusGained

    private void textoIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoIFocusLost
        pop.setVisible(false);
        try {
            textoI.setText(""+Double.parseDouble(textoI.getText()));
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    textoI.setText("" + bio.getParametros().getEsterlizacion().getIntegral());
                }
            }
        }
    }//GEN-LAST:event_textoIFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjustesEsterilizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AjustesEsterilizacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accept;
    private javax.swing.JButton Cancel;
    public static javax.swing.JTextField Histeresis;
    public static javax.swing.JTextField Tdesvio;
    public static javax.swing.JTextField Tpurga;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTextField jTextField2;
    public static javax.swing.JTextField jTextField3;
    public static javax.swing.JTextField tPulsosPurga;
    public static javax.swing.JTextField textoD;
    public static javax.swing.JTextField textoI;
    // End of variables declaration//GEN-END:variables
}
