/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.control;

import com.keyboard.JNumBoardPane;
import com.model.Bioreactor;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;

/**
 *
 * @author Fermentador 7 Litros
 */
public class AjustesOD extends javax.swing.JFrame {

    private static final long serialVersionUID = 01;
    JPopupMenu pop;
    JNumBoardPane teclado;

    /**
     * Creates new form AjustesOD
     */
    public AjustesOD() {
        initComponents();
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/com/images/logo.png")).getImage());

        for (Bioreactor bio : Variables.bioreactores) {
            if (Variables.idBioreactor == bio.getId()) {
                textPendiente.setText("" + bio.getParametros().getOd().getMOD());
                textb.setText("" + bio.getParametros().getOd().getBOD());
                HisteresisOD.setText("" + bio.getParametros().getOd().getHisteresis());
                textPromedio.setText("" + bio.getParametros().getOd().getAlpha());
                textOffset.setText("" + bio.getParametros().getOd().getOffset());
                jCheckBox1.setSelected(Variables.modbusOD);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Accept = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        textPromedio = new javax.swing.JTextField();
        textOffset = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<String>();
        HisteresisOD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textPendiente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textb = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ajustes Oxigeno Disuelto");
        setAlwaysOnTop(true);

        Accept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/symbol-check-icon.png"))); // NOI18N
        Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptActionPerformed(evt);
            }
        });

        Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/delete-icon.png"))); // NOI18N
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajustes Oxigeno Disuelto 1"));

        textPromedio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textPromedio.setText("0");
        textPromedio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textPromedioFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                textPromedioFocusGained(evt);
            }
        });

        textOffset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textOffset.setText("0");
        textOffset.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textOffsetFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                textOffsetFocusGained(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aire", "Oxigeno", "CO2", "Nitrogeno" }));

        HisteresisOD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HisteresisOD.setText("0");
        HisteresisOD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                HisteresisODFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                HisteresisODFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Tipo de Gas:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Media Movil:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Histeresis:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Offset:");

        textPendiente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textPendiente.setText("0");
        textPendiente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textPendienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textPendienteFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("m:          ");

        textb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textb.setText("0");
        textb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textbFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textbFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("b:           ");

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox1.setText("Modbus");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)
                        .addComponent(textPendiente, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textb, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(textOffset, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(HisteresisOD, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jCheckBox1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textOffset, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HisteresisOD, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textPendiente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/LogoJPSinFondo.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(Accept, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Accept, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptActionPerformed
        try {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    bio.getParametros().getOd().setOffset(Double.parseDouble(textOffset.getText()));
                    bio.getParametros().getOd().setAlpha(Double.parseDouble(textPromedio.getText()));
                    bio.getParametros().getOd().setHisteresis(Double.parseDouble(HisteresisOD.getText()));
                    bio.getParametros().getOd().setMOD(Double.parseDouble(textPendiente.getText()));
                    bio.getParametros().getOd().setBOD(Double.parseDouble(textb.getText()));
                    bio.getParametros().getOd().setTipoDeGas(jComboBox1.getSelectedIndex());
                }
            }
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }
    }//GEN-LAST:event_AcceptActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void textOffsetFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textOffsetFocusGained
        textOffset.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(textOffset);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(textOffset.getLocationOnScreen().x + textOffset.getSize().width, textOffset.getLocationOnScreen().y);
    }//GEN-LAST:event_textOffsetFocusGained

    private void textOffsetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textOffsetFocusLost
        pop.setVisible(false);
        try {
            Double.parseDouble(textOffset.getText());
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    textOffset.setText("" + bio.getParametros().getOd().getOffset());
                }
            }
        }
    }//GEN-LAST:event_textOffsetFocusLost

    private void textPromedioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textPromedioFocusGained
        textPromedio.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(textPromedio);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(textPromedio.getLocationOnScreen().x + textPromedio.getSize().width, textPromedio.getLocationOnScreen().y);
    }//GEN-LAST:event_textPromedioFocusGained

    private void textPromedioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textPromedioFocusLost
        pop.setVisible(false);
        try {
            textPromedio.setText("" + Double.parseDouble(textPromedio.getText()));
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    textPromedio.setText("" + bio.getParametros().getOd().getAlpha());
                }
            }
        }
    }//GEN-LAST:event_textPromedioFocusLost

    private void HisteresisODFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_HisteresisODFocusLost
        pop.setVisible(false);
        try {
            HisteresisOD.setText("" + Integer.parseInt(HisteresisOD.getText()));
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    HisteresisOD.setText("" + (int) bio.getParametros().getOd().getHisteresis());
                }
            }
        }
    }//GEN-LAST:event_HisteresisODFocusLost

    private void HisteresisODFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_HisteresisODFocusGained
        HisteresisOD.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(HisteresisOD);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(HisteresisOD.getLocationOnScreen().x + HisteresisOD.getSize().width, HisteresisOD.getLocationOnScreen().y);
    }//GEN-LAST:event_HisteresisODFocusGained

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void textPendienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textPendienteFocusGained
        textPendiente.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(textPendiente);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(textPendiente.getLocationOnScreen().x + textPendiente.getSize().width, textPendiente.getLocationOnScreen().y);
    }//GEN-LAST:event_textPendienteFocusGained

    private void textPendienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textPendienteFocusLost
        pop.setVisible(false);
        try {
            textPendiente.setText("" + Double.parseDouble(textPendiente.getText()));
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    textPendiente.setText("" + bio.getParametros().getOd().getMOD());
                }
            }
        }
    }//GEN-LAST:event_textPendienteFocusLost

    private void textbFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textbFocusGained
        textb.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(textb);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(textb.getLocationOnScreen().x + textb.getSize().width, textb.getLocationOnScreen().y);
    }//GEN-LAST:event_textbFocusGained

    private void textbFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textbFocusLost
        pop.setVisible(false);
        try {
            textb.setText("" + Double.parseDouble(textb.getText()));
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    textb.setText("" + bio.getParametros().getOd().getBOD());
                }
            }
        }
    }//GEN-LAST:event_textbFocusLost

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        Variables.modbusOD = jCheckBox1.isSelected();
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjustesOD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AjustesOD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accept;
    private javax.swing.JButton Cancel;
    public static javax.swing.JTextField HisteresisOD;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    public static javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTextField textOffset;
    public static javax.swing.JTextField textPendiente;
    public static javax.swing.JTextField textPromedio;
    public static javax.swing.JTextField textb;
    // End of variables declaration//GEN-END:variables
}
