/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.control;

import static com.control.AjustesPresion.AjustePc;
import com.keyboard.JNumBoardPane;
import com.model.Bioreactor;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;

/**
 *
 * @author Fermentador 7 Litros
 */
public class AjustesPresion extends javax.swing.JFrame {

    private static final long serialVersionUID = 01;
    JPopupMenu pop;
    JNumBoardPane teclado;
    public int limite = 4;

    /**
     * Creates new form AjustesControlTemperatura
     */
    public AjustesPresion() {
        initComponents();
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/com/images/logo.png")).getImage());
        for (Bioreactor bio : Variables.bioreactores) {
            if (Variables.idBioreactor == bio.getId()) {
                AjustePc.setText("" + bio.getParametros().getPresion().getAjustePresionCamara());
                Atmosferica.setText("" + bio.getParametros().getPresion().getPresionAtmosferica());
                AjustePp.setText("" + bio.getParametros().getPresion().getAjustePresionPreCamara());
                Media.setText("" + bio.getParametros().getPresion().getAlpha());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Accept = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AjustePp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AjustePc = new javax.swing.JTextField();
        Atmosferica = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Media = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JP-Biolab  Fermentors & Bioreactors");
        setAlwaysOnTop(true);
        setResizable(false);

        jPanel1.setFocusable(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/LogoJPSinFondo.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);

        Accept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/symbol-check-icon.png"))); // NOI18N
        Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptActionPerformed(evt);
            }
        });

        Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/delete-icon.png"))); // NOI18N
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajustes Control de Presión"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Ajuste de Presión Camara:");

        AjustePp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AjustePp.setText("0");
        AjustePp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                AjustePpFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                AjustePpFocusGained(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Media Movil:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Ajuste de Presión PreCamara:");

        AjustePc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AjustePc.setText("0");
        AjustePc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                AjustePcFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                AjustePcFocusGained(evt);
            }
        });

        Atmosferica.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Atmosferica.setText("0");
        Atmosferica.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AtmosfericaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AtmosfericaFocusLost(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Presión Atmosferica:");

        Media.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Media.setText("0");
        Media.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MediaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MediaFocusLost(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("kPa");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("kPa");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("kPa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AjustePc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(AjustePp, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Media, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Atmosferica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AjustePc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel1))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AjustePp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel3))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Atmosferica, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel15))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Media, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 33, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Accept, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214)
                .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Accept, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptActionPerformed
        try {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    bio.getParametros().getPresion().setAjustePresionCamara(Double.parseDouble(AjustePc.getText()));
                    bio.getParametros().getPresion().setPresionAtmosferica(Integer.parseInt(Atmosferica.getText()));
                    bio.getParametros().getPresion().setAjustePresionPreCamara(Double.parseDouble(AjustePp.getText()));
                    bio.getParametros().getPresion().setAlpha(Double.parseDouble(Media.getText()));
                }
            }
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }
    }//GEN-LAST:event_AcceptActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void AjustePcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AjustePcFocusGained
        AjustePc.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(AjustePc);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(AjustePc.getLocationOnScreen().x + AjustePc.getSize().width, AjustePc.getLocationOnScreen().y);
    }//GEN-LAST:event_AjustePcFocusGained

    private void AjustePcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AjustePcFocusLost
        pop.setVisible(false);
        try {
            Double.parseDouble(AjustePc.getText());
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    AjustePc.setText("" + (int)bio.getParametros().getPresion().getAjustePresionCamara());
                }
            }
        }
    }//GEN-LAST:event_AjustePcFocusLost

    private void AtmosfericaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AtmosfericaFocusGained
        Atmosferica.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(Atmosferica);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(Atmosferica.getLocationOnScreen().x + Atmosferica.getSize().width, Atmosferica.getLocationOnScreen().y);
    }//GEN-LAST:event_AtmosfericaFocusGained

    private void AtmosfericaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AtmosfericaFocusLost
        pop.setVisible(false);
        try {
            Atmosferica.setText("" + Integer.parseInt(Atmosferica.getText()));
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    Atmosferica.setText("" + (int)bio.getParametros().getPresion().getPresionAtmosferica());
                }
            }
        }
    }//GEN-LAST:event_AtmosfericaFocusLost

    private void AjustePpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AjustePpFocusGained
        AjustePp.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(AjustePp);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(AjustePp.getLocationOnScreen().x + AjustePp.getSize().width, AjustePp.getLocationOnScreen().y);
    }//GEN-LAST:event_AjustePpFocusGained

    private void AjustePpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AjustePpFocusLost
        pop.setVisible(false);
        try {
            AjustePp.setText("" + Integer.parseInt(AjustePp.getText()));
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    AjustePp.setText("" + (int) bio.getParametros().getPresion().getAjustePresionPreCamara());
                }
            }
        }
    }//GEN-LAST:event_AjustePpFocusLost

    private void MediaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MediaFocusGained
        Media.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(Media);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(Media.getLocationOnScreen().x + Media.getSize().width, Media.getLocationOnScreen().y);
    }//GEN-LAST:event_MediaFocusGained

    private void MediaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MediaFocusLost
        pop.setVisible(false);
        try {
            Double.parseDouble(Media.getText());
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    Media.setText("" + bio.getParametros().getPresion().getAlpha());
                }
            }
        }
    }//GEN-LAST:event_MediaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjustesPresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AjustesPresion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accept;
    public static javax.swing.JTextField AjustePc;
    public static javax.swing.JTextField AjustePp;
    public static javax.swing.JTextField Atmosferica;
    private javax.swing.JButton Cancel;
    public static javax.swing.JTextField Media;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
