/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.control;

import static com.control.AjustesControlTemperatura.jTextField1;
import com.keyboard.JNumBoardPane;
import com.model.Bioreactor;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;

/**
 *
 * @author Fermentador 7 Litros
 */
public class AjustesControlTemperatura extends javax.swing.JFrame {

    private static final long serialVersionUID = 01;
    JPopupMenu pop;
    JNumBoardPane teclado;
    public int limite = 4;

    /**
     * Creates new form AjustesControlTemperatura
     */
    public AjustesControlTemperatura() {
        initComponents();
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/com/images/logo.png")).getImage());
        for (Bioreactor bio : Variables.bioreactores) {
            if (Variables.idBioreactor == bio.getId()) {
                jTextField1.setText("" + bio.getParametros().getTemperatura().getDesvio());
                jTextField2.setText("" + bio.getParametros().getTemperatura().getGanancia2());
                jTextField3.setText("" + bio.getParametros().getTemperatura().getTCiclo());
                jTextField4.setText("" + bio.getParametros().getTemperatura().getOffset());
                jTextField5.setText("" + bio.getParametros().getTemperatura().getAlpha());
                Histeresis.setText("" + bio.getParametros().getTemperatura().getHisteresis());
                textoD.setText("" + bio.getParametros().getTemperatura().getDerivativo());
                textoI.setText("" + bio.getParametros().getTemperatura().getIntegral());
                textPendiente.setText("" + bio.getParametros().getTemperatura().getMTem());
                textb.setText("" + bio.getParametros().getTemperatura().getBTem());
                BandaInferior.setText("" + bio.getParametros().getTemperatura().getBandaInferior());
                BandaSuperior.setText("" + bio.getParametros().getTemperatura().getBandaSuperior());
                CheckBoxIntercambiador.setSelected(bio.getParametros().getTemperatura().isControlIntercambiador());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Accept = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Histeresis = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textoD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textoI = new javax.swing.JTextField();
        textPendiente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textb = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BandaSuperior = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        BandaInferior = new javax.swing.JTextField();
        CheckBoxIntercambiador = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JP-Biolab  Fermentors & Bioreactors");
        setAlwaysOnTop(true);
        setResizable(false);

        jPanel1.setFocusable(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Logo JP2.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);

        Accept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/symbol-check-icon.png"))); // NOI18N
        Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptActionPerformed(evt);
            }
        });

        Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/delete-icon.png"))); // NOI18N
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajustes Temperatura"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Desvio:");

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField3.setText("0");
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Media Movil:");

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField5.setText("0");
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Offset:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("T. Ciclo:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setText("0");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.setText("0");
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Ganancia:");

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField4.setText("0");
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Histeresis:");

        Histeresis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Histeresis.setText("0");
        Histeresis.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                HisteresisFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                HisteresisFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("D:");

        textoD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoD.setText("0");
        textoD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textoDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoDFocusLost(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("I:");

        textoI.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoI.setText("0");
        textoI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textoIFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoIFocusLost(evt);
            }
        });

        textPendiente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textPendiente.setText("0");
        textPendiente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textPendienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textPendienteFocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("m:");

        textb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textb.setText("0");
        textb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textbFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textbFocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("b:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("B. Superior:");

        BandaSuperior.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BandaSuperior.setText("0");
        BandaSuperior.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BandaSuperiorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BandaSuperiorFocusLost(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("B. Inferior:");

        BandaInferior.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BandaInferior.setText("0");
        BandaInferior.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BandaInferiorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BandaInferiorFocusLost(evt);
            }
        });

        CheckBoxIntercambiador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckBoxIntercambiador.setSelected(true);
        CheckBoxIntercambiador.setText("Intercambiador?");
        CheckBoxIntercambiador.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CheckBoxIntercambiadorStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(168, 168, 168))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(117, 117, 117)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Histeresis, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BandaSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(161, 161, 161))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(117, 117, 117)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BandaInferior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(textb, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textPendiente, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(CheckBoxIntercambiador)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(textoD, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoI, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(Histeresis, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(textPendiente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(textb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(BandaInferior, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(BandaSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(CheckBoxIntercambiador)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(Accept, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Accept, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptActionPerformed
        try {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    bio.getParametros().getTemperatura().setDesvio(Double.parseDouble(jTextField1.getText()));
                    bio.getParametros().getTemperatura().setGanancia2(Double.parseDouble(jTextField2.getText()));
                    bio.getParametros().getTemperatura().setTCiclo(Double.parseDouble(jTextField3.getText()));
                    bio.getParametros().getTemperatura().setOffset(Double.parseDouble(jTextField4.getText()));
                    bio.getParametros().getTemperatura().setAlpha(Double.parseDouble(jTextField5.getText()));
                    bio.getParametros().getTemperatura().setHisteresis(Double.parseDouble(Histeresis.getText()));
                    bio.getParametros().getTemperatura().setDerivativo(Double.parseDouble(textoD.getText()));
                    bio.getParametros().getTemperatura().setIntegral(Double.parseDouble(textoI.getText()));
                    bio.getParametros().getTemperatura().setMTem(Double.parseDouble(textPendiente.getText()));
                    bio.getParametros().getTemperatura().setBTem(Double.parseDouble(textb.getText()));
                    bio.getParametros().getTemperatura().setBandaInferior(Double.parseDouble(BandaInferior.getText()));
                    bio.getParametros().getTemperatura().setBandaSuperior(Double.parseDouble(BandaSuperior.getText()));
                    bio.getParametros().getTemperatura().setControlIntercambiador(CheckBoxIntercambiador.isSelected());
                }
            }
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }
    }//GEN-LAST:event_AcceptActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        jTextField1.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(jTextField1);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(jTextField1.getLocationOnScreen().x + jTextField1.getSize().width, jTextField1.getLocationOnScreen().y);
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        pop.setVisible(false);
        try {
            Double.parseDouble(jTextField1.getText());
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    jTextField1.setText("" + bio.getParametros().getTemperatura().getDesvio());
                }
            }
        }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        jTextField2.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(jTextField2);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(jTextField2.getLocationOnScreen().x + jTextField2.getSize().width, jTextField2.getLocationOnScreen().y);
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        pop.setVisible(false);
        try {
            jTextField2.setText("" + Integer.parseInt(jTextField2.getText()));
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    jTextField2.setText("" + bio.getParametros().getTemperatura().getGanancia2());
                }
            }
        }
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
        jTextField3.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(jTextField3);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(jTextField3.getLocationOnScreen().x + jTextField3.getSize().width, jTextField3.getLocationOnScreen().y);
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        pop.setVisible(false);
        try {
            jTextField3.setText("" + Integer.parseInt(jTextField3.getText()));
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    jTextField3.setText("" + bio.getParametros().getTemperatura().getTCiclo());
                }
            }
        }
    }//GEN-LAST:event_jTextField3FocusLost

    private void jTextField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusGained
        jTextField4.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(jTextField4);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(jTextField4.getLocationOnScreen().x + jTextField4.getSize().width, jTextField4.getLocationOnScreen().y);
    }//GEN-LAST:event_jTextField4FocusGained

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        pop.setVisible(false);
        try {
            Double.parseDouble(jTextField4.getText());
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    jTextField4.setText("" + bio.getParametros().getTemperatura().getOffset());
                }
            }
        }
    }//GEN-LAST:event_jTextField4FocusLost

    private void jTextField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusGained
        jTextField5.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(jTextField5);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(jTextField5.getLocationOnScreen().x + jTextField5.getSize().width, jTextField5.getLocationOnScreen().y);
    }//GEN-LAST:event_jTextField5FocusGained

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
        pop.setVisible(false);
        try {
            Double.parseDouble(jTextField5.getText());
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    jTextField5.setText("" + bio.getParametros().getTemperatura().getAlpha());
                }
            }
        }
    }//GEN-LAST:event_jTextField5FocusLost

    private void HisteresisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_HisteresisFocusLost
        pop.setVisible(false);
        try {
            Double.parseDouble(Histeresis.getText());
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    Histeresis.setText("" + bio.getParametros().getTemperatura().getHisteresis());
                }
            }
        }
    }//GEN-LAST:event_HisteresisFocusLost

    private void HisteresisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_HisteresisFocusGained
        Histeresis.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(Histeresis);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(Histeresis.getLocationOnScreen().x + Histeresis.getSize().width, Histeresis.getLocationOnScreen().y);
    }//GEN-LAST:event_HisteresisFocusGained

    private void textoDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoDFocusGained
        textoD.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(textoD);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(textoD.getLocationOnScreen().x + textoD.getSize().width, textoD.getLocationOnScreen().y);
    }//GEN-LAST:event_textoDFocusGained

    private void textoDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoDFocusLost
        pop.setVisible(false);
        try {
            Variables.derivativo = Double.parseDouble(textoD.getText());
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    textoD.setText("" + bio.getParametros().getTemperatura().getDerivativo());
                }
            }
        }
    }//GEN-LAST:event_textoDFocusLost

    private void textoIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoIFocusGained
        textoI.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(textoI);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(textoI.getLocationOnScreen().x + textoI.getSize().width, textoI.getLocationOnScreen().y);
    }//GEN-LAST:event_textoIFocusGained

    private void textoIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoIFocusLost
        pop.setVisible(false);
        try {
            Variables.integral = Double.parseDouble(textoI.getText());
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    textoI.setText("" + bio.getParametros().getTemperatura().getIntegral());
                }
            }
        }
    }//GEN-LAST:event_textoIFocusLost

    private void textPendienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textPendienteFocusGained
        textPendiente.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(textPendiente);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(textPendiente.getLocationOnScreen().x + textPendiente.getSize().width, textPendiente.getLocationOnScreen().y);
    }//GEN-LAST:event_textPendienteFocusGained

    private void textPendienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textPendienteFocusLost
        pop.setVisible(false);
        try {
            textPendiente.setText("" + Double.parseDouble(textPendiente.getText()));
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    textPendiente.setText("" + bio.getParametros().getTemperatura().getMTem());
                }
            }
        }
    }//GEN-LAST:event_textPendienteFocusLost

    private void textbFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textbFocusGained
        textb.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(textb);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(textb.getLocationOnScreen().x + textb.getSize().width, textb.getLocationOnScreen().y);
    }//GEN-LAST:event_textbFocusGained

    private void textbFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textbFocusLost
        pop.setVisible(false);
        try {
            textb.setText("" + Double.parseDouble(textb.getText()));
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    textb.setText("" + bio.getParametros().getTemperatura().getBTem());
                }
            }
        }
    }//GEN-LAST:event_textbFocusLost

    private void BandaSuperiorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BandaSuperiorFocusGained
        BandaSuperior.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(BandaSuperior);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(BandaSuperior.getLocationOnScreen().x + BandaSuperior.getSize().width, BandaSuperior.getLocationOnScreen().y);
    }//GEN-LAST:event_BandaSuperiorFocusGained

    private void BandaSuperiorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BandaSuperiorFocusLost
        pop.setVisible(false);
        try {
            BandaSuperior.setText("" + Double.parseDouble(BandaSuperior.getText()));
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    BandaSuperior.setText("" + bio.getParametros().getTemperatura().getBandaSuperior());
                }
            }
        }
    }//GEN-LAST:event_BandaSuperiorFocusLost

    private void BandaInferiorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BandaInferiorFocusGained
        BandaInferior.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(BandaInferior);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(BandaInferior.getLocationOnScreen().x + BandaInferior.getSize().width, BandaInferior.getLocationOnScreen().y);
    }//GEN-LAST:event_BandaInferiorFocusGained

    private void BandaInferiorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BandaInferiorFocusLost
        pop.setVisible(false);
        try {
            BandaInferior.setText("" + Double.parseDouble(BandaInferior.getText()));
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    BandaInferior.setText("" + bio.getParametros().getTemperatura().getBandaInferior());
                }
            }
        }
    }//GEN-LAST:event_BandaInferiorFocusLost

    private void CheckBoxIntercambiadorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CheckBoxIntercambiadorStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxIntercambiadorStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjustesControlTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AjustesControlTemperatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accept;
    public static javax.swing.JTextField BandaInferior;
    public static javax.swing.JTextField BandaSuperior;
    private javax.swing.JButton Cancel;
    private javax.swing.JCheckBox CheckBoxIntercambiador;
    public static javax.swing.JTextField Histeresis;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTextField jTextField1;
    public static javax.swing.JTextField jTextField2;
    public static javax.swing.JTextField jTextField3;
    public static javax.swing.JTextField jTextField4;
    public static javax.swing.JTextField jTextField5;
    public static javax.swing.JTextField textPendiente;
    public static javax.swing.JTextField textb;
    public static javax.swing.JTextField textoD;
    public static javax.swing.JTextField textoI;
    // End of variables declaration//GEN-END:variables
}
