/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.control;

import com.keyboard.JNumBoardPane;
import com.model.Bioreactor;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;

/**
 *
 * @author Fermentador 7 Litros
 */
public class AjustesEsterilizacion extends javax.swing.JFrame {

    private static final long serialVersionUID = 01;
    JPopupMenu pop;
    JNumBoardPane teclado;
    public int limite = 4;

    /**
     * Creates new form AjustesControlTemperatura
     */
    public AjustesEsterilizacion() {
        initComponents();
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/com/images/logo.png")).getImage());
        for (Bioreactor bio : Variables.bioreactores) {
            if (Variables.idBioreactor == bio.getId()) {
                tPulsosPurga.setText("" + bio.getParametros().getEsterlizacion().getPulsosPurga());
                Tpurga.setText("" + bio.getParametros().getEsterlizacion().getTPurga());
                Histeresis.setText("" + bio.getParametros().getEsterlizacion().getHisteresis());
                Tdesvio.setText("" + bio.getParametros().getEsterlizacion().getDesvio());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Accept = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Tpurga = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tPulsosPurga = new javax.swing.JTextField();
        Tdesvio = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Histeresis = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JP-Biolab  Fermentors & Bioreactors");
        setAlwaysOnTop(true);
        setResizable(false);

        jPanel1.setFocusable(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/LogoJPSinFondo.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);

        Accept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/symbol-check-icon.png"))); // NOI18N
        Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptActionPerformed(evt);
            }
        });

        Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/delete-icon.png"))); // NOI18N
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajustes Control de Esterilización"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Temperatura de purga:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        Tpurga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tpurga.setText("0");
        Tpurga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TpurgaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TpurgaFocusLost(evt);
            }
        });
        jPanel2.add(Tpurga, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 91, 31));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("°C");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Pulsos Purga:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        tPulsosPurga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tPulsosPurga.setText("0");
        tPulsosPurga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tPulsosPurgaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tPulsosPurgaFocusLost(evt);
            }
        });
        jPanel2.add(tPulsosPurga, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 91, 31));

        Tdesvio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tdesvio.setText("0");
        Tdesvio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TdesvioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TdesvioFocusLost(evt);
            }
        });
        jPanel2.add(Tdesvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 91, 31));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("°C");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Desvio:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        Histeresis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Histeresis.setText("0");
        Histeresis.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                HisteresisFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                HisteresisFocusLost(evt);
            }
        });
        jPanel2.add(Histeresis, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 91, 31));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Histeresis:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("°C");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, -1, -1));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jSeparator1)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(123, 123, 123)
                                .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 707, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(242, 242, 242)
                                .add(Accept, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 103, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(214, 214, 214)
                                .add(Cancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 103, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(7, 7, 7)
                .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 54, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(Accept, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Cancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptActionPerformed
        try {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    bio.getParametros().getEsterlizacion().setTPurga(Double.parseDouble(Tpurga.getText()));
                    bio.getParametros().getEsterlizacion().setDesvio(Double.parseDouble(Tdesvio.getText()));
                    bio.getParametros().getEsterlizacion().setHisteresis(Double.parseDouble(Histeresis.getText()));
                    bio.getParametros().getEsterlizacion().setPulsosPurga(Integer.parseInt(tPulsosPurga.getText()));
                }
            }
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }
    }//GEN-LAST:event_AcceptActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void TpurgaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TpurgaFocusGained
        Tpurga.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(Tpurga);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(Tpurga.getLocationOnScreen().x + Tpurga.getSize().width, Tpurga.getLocationOnScreen().y);
    }//GEN-LAST:event_TpurgaFocusGained

    private void TpurgaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TpurgaFocusLost
        pop.setVisible(false);
        try {
            Double.parseDouble(Tpurga.getText());
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    Tpurga.setText("" + bio.getParametros().getEsterlizacion().getTPurga());
                }
            }
        }
    }//GEN-LAST:event_TpurgaFocusLost

    private void tPulsosPurgaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tPulsosPurgaFocusGained
        tPulsosPurga.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(tPulsosPurga);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(tPulsosPurga.getLocationOnScreen().x + tPulsosPurga.getSize().width, tPulsosPurga.getLocationOnScreen().y);
    }//GEN-LAST:event_tPulsosPurgaFocusGained

    private void tPulsosPurgaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tPulsosPurgaFocusLost
        pop.setVisible(false);
        try {
            Integer.parseInt(tPulsosPurga.getText());
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    tPulsosPurga.setText("" + bio.getParametros().getEsterlizacion().getPulsosPurga());
                }
            }
        }
    }//GEN-LAST:event_tPulsosPurgaFocusLost

    private void TdesvioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TdesvioFocusGained
        Tdesvio.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(Tdesvio);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(Tdesvio.getLocationOnScreen().x + Tdesvio.getSize().width, Tdesvio.getLocationOnScreen().y);
    }//GEN-LAST:event_TdesvioFocusGained

    private void TdesvioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TdesvioFocusLost
        pop.setVisible(false);
        try {
            Double.parseDouble(Tdesvio.getText());
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    Tdesvio.setText("" + bio.getParametros().getEsterlizacion().getDesvio());
                }
            }
        }
    }//GEN-LAST:event_TdesvioFocusLost

    private void HisteresisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_HisteresisFocusGained
        Histeresis.setText(null);
        pop = new JPopupMenu();
        teclado = new JNumBoardPane(Histeresis);
        pop.add(teclado);
        pop.setVisible(true);
        pop.setLocation(Histeresis.getLocationOnScreen().x + Histeresis.getSize().width, Histeresis.getLocationOnScreen().y);
    }//GEN-LAST:event_HisteresisFocusGained

    private void HisteresisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_HisteresisFocusLost
        pop.setVisible(false);
        try {
            Double.parseDouble(Histeresis.getText());
        } catch (Exception e) {
            for (Bioreactor bio : Variables.bioreactores) {
                if (Variables.idBioreactor == bio.getId()) {
                    Histeresis.setText("" + bio.getParametros().getEsterlizacion().getDesvio());
                }
            }
        }
    }//GEN-LAST:event_HisteresisFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjustesEsterilizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AjustesEsterilizacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accept;
    private javax.swing.JButton Cancel;
    public static javax.swing.JTextField Histeresis;
    public static javax.swing.JTextField Tdesvio;
    public static javax.swing.JTextField Tpurga;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTextField tPulsosPurga;
    // End of variables declaration//GEN-END:variables
}
